
-- HL7 Name Types
-- https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.810

-- Type_ID     - contains a local application Name Type ID.
-- Description - contains the "Concept Name" that so far correspond to "Prefered Concept Name"
-- Category_ID - is used for the "Concept Code"

INSERT INTO [Entity].[Name_Type] ([Type_ID], [Description], [CodeSet_Name]) VALUES
   ('C','Adopted Name','Name type (HL7)'),
   ('A','Alias Name','Name type (HL7)'),
   ('K','Artist Name','Name type (HL7)'),
   ('S','Coded Pseudo-Name to ensure anonymity','Name type (HL7)'),
   ('D','Display Name','Name type (HL7)'),
   ('T','Indigenous/Tribal/Community Name','Name type (HL7)'),
   ('L','Legal Name','Name type (HL7)'),
   ('I','Licensing Name','Name type (HL7)'),
   ('M','Maiden Name','Name type (HL7)'),
   ('B','Name at Birth','Name type (HL7)'),
   ('P','Name of Partner/Spouse (retained for backward compatibility only)','Name type (HL7)'),
   ('N','Nickname /_Call me_ Name/Street Name','Name type (HL7)'),
   ('R','Registered Name (animals only)','Name type (HL7)'),
   ('U','Unspecified','Name type (HL7)')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Name_Type]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'CDC',
       Version_Number = 'v2'
GO

-- HL7 Religion Code v1
INSERT INTO [Entity].[Religion_Code] ([Type_ID], [Description], [CodeSet_Name]) VALUES
   ('AGN','Agnostic','Religion (HL7)'),
   ('ATH','Atheist','Religion (HL7)'),
   ('BAH','Baha''i','Religion (HL7)'),
   ('BUD','Buddhist','Religion (HL7)'),
   ('BMA','Buddhist: Mahayana','Religion (HL7)'),
   ('BOT','Buddhist: Other','Religion (HL7)'),
   ('BTA','Buddhist: Tantrayana','Religion (HL7)'),
   ('BTH','Buddhist: Theravada','Religion (HL7)'),
   ('CFR','Chinese Folk Religionist','Religion (HL7)'),
   ('CHR','Christian','Religion (HL7)'),
   ('AMT','Christian: African Methodist Episcopal','Religion (HL7)'),
   ('AME','Christian: African Methodist Episcopal Zion','Religion (HL7)'),
   ('ABC','Christian: American Baptist Church','Religion (HL7)'),
   ('ANG','Christian: Anglican','Religion (HL7)'),
   ('AOG','Christian: Assembly of God','Religion (HL7)'),
   ('BAP','Christian: Baptist','Religion (HL7)'),
   ('CMA','Christian: Christian Missionary Alliance','Religion (HL7)'),
   ('CRR','Christian: Christian Reformed','Religion (HL7)'),
   ('CHS','Christian: Christian Science','Religion (HL7)'),
   ('COC','Christian: Church of Christ','Religion (HL7)'),
   ('COG','Christian: Church of God','Religion (HL7)'),
   ('COI','Christian: Church of God in Christ','Religion (HL7)'),
   ('NAZ','Christian: Church of the Nazarene','Religion (HL7)'),
   ('COM','Christian: Community','Religion (HL7)'),
   ('COL','Christian: Congregational','Religion (HL7)'),
   ('EOT','Christian: Eastern Orthodox','Religion (HL7)'),
   ('EPI','Christian: Episcopalian','Religion (HL7)'),
   ('EVC','Christian: Evangelical Church','Religion (HL7)'),
   ('FWB','Christian: Free Will Baptist','Religion (HL7)'),
   ('FRQ','Christian: Friends','Religion (HL7)'),
   ('QUA','Christian: Friends','Religion (HL7)'),
   ('GRE','Christian: Greek Orthodox','Religion (HL7)'),
   ('JWN','Christian: Jehovah''s Witness','Religion (HL7)'),
   ('MOM','Christian: Latter-day Saints','Religion (HL7)'),
   ('LUT','Christian: Lutheran','Religion (HL7)'),
   ('LMS','Christian: Lutheran Missouri Synod','Religion (HL7)'),
   ('MEN','Christian: Mennonite','Religion (HL7)'),
   ('MET','Christian: Methodist','Religion (HL7)'),
   ('ORT','Christian: Orthodox','Religion (HL7)'),
   ('COT','Christian: Other','Religion (HL7)'),
   ('COP','Christian: Other Pentecostal','Religion (HL7)'),
   ('PRC','Christian: Other Protestant','Religion (HL7)'),
   ('PEN','Christian: Pentecostal','Religion (HL7)'),
   ('PRE','Christian: Presbyterian','Religion (HL7)'),
   ('PRO','Christian: Protestant','Religion (HL7)'),
   ('REC','Christian: Reformed Church','Religion (HL7)'),
   ('REO','Christian: Reorganized Church of Jesus Christ-LDS','Religion (HL7)'),
   ('CAT','Christian: Roman Catholic','Religion (HL7)'),
   ('SAA','Christian: Salvation Army','Religion (HL7)'),
   ('SEV','Christian: Seventh Day Adventist','Religion (HL7)'),
   ('SOU','Christian: Southern Baptist','Religion (HL7)'),
   ('UNI','Christian: Unitarian','Religion (HL7)'),
   ('UNU','Christian: Unitarian Universalist','Religion (HL7)'),
   ('UCC','Christian: United Church of Christ','Religion (HL7)'),
   ('UMD','Christian: United Methodist','Religion (HL7)'),
   ('WES','Christian: Wesleyan','Religion (HL7)'),
   ('WMC','Christian: Wesleyan Methodist','Religion (HL7)'),
   ('CNF','Confucian','Religion (HL7)'),
   ('ERL','Ethnic Religionist','Religion (HL7)'),
   ('HIN','Hindu','Religion (HL7)'),
   ('HOT','Hindu: Other','Religion (HL7)'),
   ('HSH','Hindu: Shaivites','Religion (HL7)'),
   ('HVA','Hindu: Vaishnavites','Religion (HL7)'),
   ('JAI','Jain','Religion (HL7)'),
   ('JEW','Jewish','Religion (HL7)'),
   ('JCO','Jewish: Conservative','Religion (HL7)'),
   ('JOR','Jewish: Orthodox','Religion (HL7)'),
   ('JOT','Jewish: Other','Religion (HL7)'),
   ('JRC','Jewish: Reconstructionist','Religion (HL7)'),
   ('JRF','Jewish: Reform','Religion (HL7)'),
   ('JRN','Jewish: Renewal','Religion (HL7)'),
   ('MOS','Muslim','Religion (HL7)'),
   ('MOT','Muslim: Other','Religion (HL7)'),
   ('MSH','Muslim: Shiite','Religion (HL7)'),
   ('MSU','Muslim: Sunni','Religion (HL7)'),
   ('NAM','Native American','Religion (HL7)'),
   ('NRL','New Religionist','Religion (HL7)'),
   ('NOE','Nonreligious','Religion (HL7)'),
   ('OTH','Other','Religion (HL7)'),
   ('SHN','Shintoist','Religion (HL7)'),
   ('SIK','Sikh','Religion (HL7)'),
   ('SPI','Spiritist','Religion (HL7)'),
   ('VAR','Unknown','Religion (HL7)')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Religion_Code]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'CDC',
       Version_Number = 'v1'
GO

-- HL7 Race Code
INSERT INTO [Entity].[Race_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('1002-5', 'American Indian or Alaska Native', 'Race - CDC'),
   ('2028-9', 'Asian', 'Race - CDC'),
   ('2054-5', 'Black or African American', 'Race - CDC'),
   ('2076-8', 'Native Hawaiian or Other Pacific Islander', 'Race - CDC'),
   ('2131-1', 'Other Race', 'Race - CDC'),
   ('2106-3', 'White', 'Race - CDC'),
   ('unknown', 'unknown', 'Race - CDC')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Race_Code]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'CDC',
       Version_Number = 'v1'
GO

-- HL7 Ethnicity Code
INSERT INTO [Entity].[Ethnicity_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('2135-2', 'Hispanic or Latino', 'Ethnicity - CDC'),
   ('2186-5', 'Not Hispanic or Latino', 'Ethnicity - CDC'),
   ('OTH', 'other', 'Ethnicity - HL7'),
   ('UNK', 'unknown', 'Ethnicity - HL7')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Ethnicity_Code]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'CDC',
       Version_Number = 'v2'
GO

-- HL7 Sex Code
INSERT INTO [Entity].[Sex_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('F', 'Female', 'Administrative sex (HL7)'),
   ('M', 'Male', 'Administrative sex (HL7)'),
   ('U', 'Unknown', 'Administrative sex (HL7)')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Ethnicity_Code]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'HL7',
       Version_Number = 'v1'
GO

-- Census Industry v1
INSERT INTO [Entity].[Industry_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('7280','Accounting, tax preparation, bookkeeping, and payroll services','Industry CDC Census 2010'),
   ('9570','Administration of economic programs and space research','Industry CDC Census 2010'),
   ('9490','Administration of environmental quality and housing programs','Industry CDC Census 2010'),
   ('9480','Administration of human resource programs','Industry CDC Census 2010'),
   ('7470','Advertising and related services','Industry CDC Census 2010'),
   ('3590','Aerospace products and parts manufacturing','Industry CDC Census 2010'),
   ('2180','Agricultural chemical manufacturing','Industry CDC Census 2010'),
   ('3070','Agricultural implement manufacturing','Industry CDC Census 2010'),
   ('6070','Air transportation','Industry CDC Census 2010'),
   ('3580','Aircraft and parts manufacturing','Industry CDC Census 2010'),
   ('4560','Alcoholic beverages merchant wholesalers','Industry CDC Census 2010'),
   ('2680','Aluminum production and processing','Industry CDC Census 2010'),
   ('1070','Animal food, grain and oilseed milling','Industry CDC Census 2010'),
   ('0180','Animal production','Industry CDC Census 2010'),
   ('1180','Animal slaughtering and processing','Industry CDC Census 2010'),
   ('1690','Apparel accessories and other apparel manufacturing','Industry CDC Census 2010'),
   ('4390','Apparel, fabrics, and notions merchant wholesalers','Industry CDC Census 2010'),
   ('7290','Architectural, engineering, and related services','Industry CDC Census 2010'),
   ('4690','Auto parts, accessories, and tire stores','Industry CDC Census 2010'),
   ('4670','Automobile dealers','Industry CDC Census 2010'),
   ('7080','Automotive equipment rental and leasing','Industry CDC Census 2010'),
   ('8770','Automotive repair and maintenance','Industry CDC Census 2010'),
   ('1270','Bakeries, except retail','Industry CDC Census 2010'),
   ('6870','Banking and related activities','Industry CDC Census 2010'),
   ('8970','Barber shops','Industry CDC Census 2010'),
   ('8980','Beauty salons','Industry CDC Census 2010'),
   ('4990','Beer, wine, and liquor stores','Industry CDC Census 2010'),
   ('1370','Beverage manufacturing','Industry CDC Census 2010'),
   ('5370','Book stores and news dealers','Industry CDC Census 2010'),
   ('8580','Bowling centers','Industry CDC Census 2010'),
   ('4870','Building material and supplies dealers','Industry CDC Census 2010'),
   ('6180','Bus service and urban transit','Industry CDC Census 2010'),
   ('7590','Business support services','Industry CDC Census 2010'),
   ('9190','Business, professional, political, and similar organizations','Industry CDC Census 2010'),
   ('7880','Business, technical, and trade schools and training','Industry CDC Census 2010'),
   ('8780','Car washes','Industry CDC Census 2010'),
   ('1570','Carpet and rug mills','Industry CDC Census 2010'),
   ('2570','Cement, concrete, lime, and gypsum product manufacturing','Industry CDC Census 2010'),
   ('8470','Child day care services','Industry CDC Census 2010'),
   ('9170','Civic, social, advocacy organizations, and grantmaking and giving services','Industry CDC Census 2010'),
   ('5170','Clothing stores','Industry CDC Census 2010'),
   ('0380','Coal mining','Industry CDC Census 2010'),
   ('2890','Coating, engraving, heat treating and allied activities','Industry CDC Census 2010'),
   ('7870','Colleges and universities, including junior colleges','Industry CDC Census 2010'),
   ('8870','Commercial and industrial machinery and equipment repair and maintenance','Industry CDC Census 2010'),
   ('3090','Commercial and service industry machinery manufacturing','Industry CDC Census 2010'),
   ('7190','Commercial, industrial, and other intangible assets rental and leasing','Industry CDC Census 2010'),
   ('3370','Communications, audio, and video equipment manufacturing','Industry CDC Census 2010'),
   ('8380','Community food and housing, and emergency services','Industry CDC Census 2010'),
   ('3360','Computer and peripheral equipment manufacturing','Industry CDC Census 2010'),
   ('7380','Computer systems design and related services','Industry CDC Census 2010'),
   ('0770','Construction (the cleaning of buildings and dwellings is incidental during  construction and immediately after construction)','Industry CDC Census 2010'),
   ('3080','Construction, mining and oil and gas field machinery manufacturing','Industry CDC Census 2010'),
   ('6380','Couriers and messengers','Industry CDC Census 2010'),
   ('0170','Crop production','Industry CDC Census 2010'),
   ('1680','Cut and sew apparel manufacturing','Industry CDC Census 2010'),
   ('2790','Cutlery and hand tool manufacturing','Industry CDC Census 2010'),
   ('1170','Dairy product manufacturing','Industry CDC Census 2010'),
   ('6695','Data processing, hosting, and related services','Industry CDC Census 2010'),
   ('5380','Department stores and discount stores','Industry CDC Census 2010'),
   ('8690','Drinking places, alcoholic beverages','Industry CDC Census 2010'),
   ('4380','Drugs, sundries, and chemical and allied products merchant wholesalers','Industry CDC Census 2010'),
   ('9070','Drycleaning and laundry services','Industry CDC Census 2010'),
   ('0590','Electric and gas, and other combinations','Industry CDC Census 2010'),
   ('0570','Electric power generation, transmission and distribution','Industry CDC Census 2010'),
   ('4190','Electrical and electronic goods merchant wholesalers','Industry CDC Census 2010'),
   ('3490','Electrical lighting and electrical equipment manufacturing, and other  electrical component manufacturing, n.e.c.','Industry CDC Census 2010'),
   ('8790','Electronic and precision equipment repair and maintenance','Industry CDC Census 2010'),
   ('5591','Electronic auctions','Industry CDC Census 2010'),
   ('3390','Electronic component and product manufacturing, n.e.c.','Industry CDC Census 2010'),
   ('5590','Electronic shopping','Industry CDC Census 2010'),
   ('7860','Elementary and secondary schools','Industry CDC Census 2010'),
   ('7580','Employment services','Industry CDC Census 2010'),
   ('3180','Engines, turbines, and power transmission equipment manufacturing','Industry CDC Census 2010'),
   ('9370','Executive offices and legislative bodies','Industry CDC Census 2010'),
   ('1480','Fabric mills, except knitting','Industry CDC Census 2010'),
   ('4480','Farm product raw materials merchant wholesalers','Industry CDC Census 2010'),
   ('4570','Farm supplies merchant wholesalers','Industry CDC Census 2010'),
   ('1470','Fiber, yarn, and thread mills','Industry CDC Census 2010'),
   ('0280','Fishing, hunting, and trapping','Industry CDC Census 2010'),
   ('8890','Footwear and leather goods repair','Industry CDC Census 2010'),
   ('1770','Footwear manufacturing','Industry CDC Census 2010'),
   ('0190','Forestry except logging','Industry CDC Census 2010'),
   ('2770','Foundries','Industry CDC Census 2010'),
   ('1090','Fruit and vegetable preserving and specialty food manufacturing','Industry CDC Census 2010'),
   ('5680','Fuel dealers','Industry CDC Census 2010'),
   ('9080','Funeral homes, cemeteries, and crematories','Industry CDC Census 2010'),
   ('4080','Furniture and home furnishing merchant wholesalers','Industry CDC Census 2010'),
   ('4770','Furniture and home furnishings stores','Industry CDC Census 2010'),
   ('3890','Furniture and related product manufacturing','Industry CDC Census 2010'),
   ('5090','Gasoline stations','Industry CDC Census 2010'),
   ('5570','Gift, novelty, and souvenir shops','Industry CDC Census 2010'),
   ('2490','Glass and glass product manufacturing','Industry CDC Census 2010'),
   ('4470','Groceries and related products merchant wholesalers','Industry CDC Census 2010'),
   ('4970','Grocery stores','Industry CDC Census 2010'),
   ('4880','Hardware stores','Industry CDC Census 2010'),
   ('4260','Hardware, plumbing and heating equipment, and supplies merchant wholesalers','Industry CDC Census 2010'),
   ('5080','Health and personal care, except drug, stores','Industry CDC Census 2010'),
   ('8170','Home health care services','Industry CDC Census 2010'),
   ('8190','Hospitals','Industry CDC Census 2010'),
   ('3470','Household appliance manufacturing','Industry CDC Census 2010'),
   ('4780','Household appliance stores','Industry CDC Census 2010'),
   ('8560','Independent artists, performing arts, spectator sports, and related industries','Industry CDC Census 2010'),
   ('8370','Individual and family services','Industry CDC Census 2010'),
   ('2290','Industrial and miscellaneous chemicals','Industry CDC Census 2010'),
   ('9990','Insufficient Information','Industry CDC Census 2010'),
   ('6990','Insurance carriers and related activities','Industry CDC Census 2010'),
   ('6672','Internet publishing and broadcasting and web search portals','Industry CDC Census 2010'),
   ('7680','Investigation and security services','Industry CDC Census 2010'),
   ('2670','Iron and steel mills and steel product manufacturing','Industry CDC Census 2010'),
   ('5190','Jewelry, luggage, and leather goods stores','Industry CDC Census 2010'),
   ('9470','Justice, public order, and safety activities','Industry CDC Census 2010'),
   ('1670','Knitting fabric mills, and apparel knitting mills','Industry CDC Census 2010'),
   ('9180','Labor unions','Industry CDC Census 2010'),
   ('7770','Landscaping services','Industry CDC Census 2010'),
   ('4890','Lawn and garden equipment and supplies stores','Industry CDC Census 2010'),
   ('1790','Leather tanning and finishing and other allied products manufacturing','Industry CDC Census 2010'),
   ('7270','Legal services','Industry CDC Census 2010'),
   ('6770','Libraries and archives','Industry CDC Census 2010'),
   ('0270','Logging','Industry CDC Census 2010'),
   ('4090','Lumber and other construction materials merchant wholesalers','Industry CDC Census 2010'),
   ('2880','Machine shops; turned product; screw, nut and bolt manufacturing','Industry CDC Census 2010'),
   ('3190','Machinery manufacturing, n.e.c.','Industry CDC Census 2010'),
   ('4270','Machinery, equipment, and supplies merchant wholesalers','Industry CDC Census 2010'),
   ('5592','Mail order houses','Industry CDC Census 2010'),
   ('7570','Management of companies and enterprises','Industry CDC Census 2010'),
   ('7390','Management, scientific, and technical consulting services','Industry CDC Census 2010'),
   ('3960','Medical equipment and supplies manufacturing','Industry CDC Census 2010'),
   ('2780','Metal forgings and stampings','Industry CDC Census 2010'),
   ('0390','Metal ore mining','Industry CDC Census 2010'),
   ('4180','Metals and minerals, except petroleum, merchant wholesalers','Industry CDC Census 2010'),
   ('3170','Metalworking machinery manufacturing','Industry CDC Census 2010'),
   ('9870','Military Reserves or National Guard','Industry CDC Census 2010'),
   ('4290','Miscellaneous durable goods merchant wholesalers','Industry CDC Census 2010'),
   ('2980','Miscellaneous fabricated metal products manufacturing','Industry CDC Census 2010'),
   ('5390','Miscellaneous general merchandise stores','Industry CDC Census 2010'),
   ('3980','Miscellaneous manufacturing, n.e.c.','Industry CDC Census 2010'),
   ('4580','Miscellaneous nondurable goods merchant wholesalers','Industry CDC Census 2010'),
   ('2590','Miscellaneous nonmetallic mineral product manufacturing','Industry CDC Census 2010'),
   ('1890','Miscellaneous paper and pulp products','Industry CDC Census 2010'),
   ('2090','Miscellaneous petroleum and coal products','Industry CDC Census 2010'),
   ('5580','Miscellaneous retail stores','Industry CDC Census 2010'),
   ('3870','Miscellaneous wood products','Industry CDC Census 2010'),
   ('6570','Motion pictures and video industries','Industry CDC Census 2010'),
   ('3570','Motor vehicles and motor vehicle equipment manufacturing','Industry CDC Census 2010'),
   ('4070','Motor vehicles, parts and supplies merchant wholesalers','Industry CDC Census 2010'),
   ('8570','Museums, art galleries, historical sites, and similar institutions','Industry CDC Census 2010'),
   ('5290','Music stores','Industry CDC Census 2010'),
   ('8990','Nail salons and other personal care services','Industry CDC Census 2010'),
   ('9590','National security and international affairs','Industry CDC Census 2010'),
   ('0580','Natural gas distribution','Industry CDC Census 2010'),
   ('3380','Navigational, measuring, electromedical, and control instruments manufacturing','Industry CDC Census 2010'),
   ('6470','Newspaper publishers','Industry CDC Census 2010'),
   ('6890','Non-depository credit and related activities','Industry CDC Census 2010'),
   ('2690','Nonferrous metal, except aluminum, production and processing','Industry CDC Census 2010'),
   ('0470','Nonmetallic mineral mining and quarrying','Industry CDC Census 2010'),
   ('9890','Non-paid Worker','Industry CDC Census 2010'),
   ('1290','Not specified food industries','Industry CDC Census 2010'),
   ('3290','Not specified machinery manufacturing','Industry CDC Census 2010'),
   ('3990','Not specified manufacturing industries','Industry CDC Census 2010'),
   ('2990','Not specified metal industries','Industry CDC Census 2010'),
   ('5790','Not specified retail trade','Industry CDC Census 2010'),
   ('0480','Not specified type of mining','Industry CDC Census 2010'),
   ('0690','Not specified utilities','Industry CDC Census 2010'),
   ('4590','Not specified wholesale trade','Industry CDC Census 2010'),
   ('8270','Nursing care facilities','Industry CDC Census 2010'),
   ('5480','Office supplies and stationery stores','Industry CDC Census 2010'),
   ('7990','Offices of chiropractors','Industry CDC Census 2010'),
   ('7980','Offices of dentists','Industry CDC Census 2010'),
   ('8070','Offices of optometrists','Industry CDC Census 2010'),
   ('8080','Offices of other health practitioners','Industry CDC Census 2010'),
   ('7970','Offices of physicians','Industry CDC Census 2010'),
   ('0370','Oil and gas extraction','Industry CDC Census 2010'),
   ('2970','Ordnance','Industry CDC Census 2010'),
   ('7780','Other administrative and other support services','Industry CDC Census 2010'),
   ('8590','Other amusement, gambling, and recreation industries','Industry CDC Census 2010'),
   ('7180','Other consumer goods rental','Industry CDC Census 2010'),
   ('5690','Other direct selling establishments','Industry CDC Census 2010'),
   ('9390','Other general government and support','Industry CDC Census 2010'),
   ('8180','Other health care services','Industry CDC Census 2010'),
   ('6780','Other information services','Industry CDC Census 2010'),
   ('4680','Other motor vehicle dealers','Industry CDC Census 2010'),
   ('9090','Other personal services','Industry CDC Census 2010'),
   ('7490','Other professional, scientific, and technical services','Industry CDC Census 2010'),
   ('7890','Other schools and instruction, and educational support services','Industry CDC Census 2010'),
   ('6690','Other telecommunications services','Industry CDC Census 2010'),
   ('3690','Other transportation equipment manufacturing','Industry CDC Census 2010'),
   ('8090','Outpatient care centers','Industry CDC Census 2010'),
   ('2270','Paint, coating, and adhesive manufacturing','Industry CDC Census 2010'),
   ('4370','Paper and paper products merchant wholesalers','Industry CDC Census 2010'),
   ('1880','Paperboard containers and boxes','Industry CDC Census 2010'),
   ('6480','Periodical, book, and directory publishers','Industry CDC Census 2010'),
   ('8880','Personal and household goods repair and maintenance','Industry CDC Census 2010'),
   ('4490','Petroleum and petroleum products merchant wholesalers','Industry CDC Census 2010'),
   ('2070','Petroleum refining','Industry CDC Census 2010'),
   ('2190','Pharmaceutical and medicine manufacturing','Industry CDC Census 2010'),
   ('5070','Pharmacies and drug stores','Industry CDC Census 2010'),
   ('6270','Pipeline transportation','Industry CDC Census 2010'),
   ('2370','Plastics product manufacturing','Industry CDC Census 2010'),
   ('6370','Postal Service','Industry CDC Census 2010'),
   ('2470','Pottery, ceramics, and plumbing fixture manufacturing','Industry CDC Census 2010'),
   ('3790','Prefabricated wood buildings and mobile homes','Industry CDC Census 2010'),
   ('1990','Printing and related support activities','Industry CDC Census 2010'),
   ('9290','Private households','Industry CDC Census 2010'),
   ('4170','Professional and commercial equipment and supplies merchant wholesalers','Industry CDC Census 2010'),
   ('9380','Public finance activities','Industry CDC Census 2010'),
   ('1870','Pulp, paper, and paperboard mills','Industry CDC Census 2010'),
   ('6670','Radio and television broadcasting and cable subscription programming','Industry CDC Census 2010'),
   ('4790','Radio, TV, and computer stores','Industry CDC Census 2010'),
   ('6080','Rail transportation','Industry CDC Census 2010'),
   ('3670','Railroad rolling stock manufacturing','Industry CDC Census 2010'),
   ('7070','Real estate','Industry CDC Census 2010'),
   ('8670','Recreational vehicle parks and camps, and rooming and boarding houses','Industry CDC Census 2010'),
   ('4280','Recyclable material merchant wholesalers','Industry CDC Census 2010'),
   ('9160','Religious organizations','Industry CDC Census 2010'),
   ('8290','Residential care facilities, without nursing','Industry CDC Census 2010'),
   ('2170','Resin, synthetic rubber and fibers, and filaments manufacturing','Industry CDC Census 2010'),
   ('8680','Restaurants and other food services','Industry CDC Census 2010'),
   ('1190','Retail bakeries','Industry CDC Census 2010'),
   ('5470','Retail florists','Industry CDC Census 2010'),
   ('9880','Retired','Industry CDC Census 2010'),
   ('2390','Rubber products, except tires, manufacturing','Industry CDC Census 2010'),
   ('6880','Savings institutions, including credit unions','Industry CDC Census 2010'),
   ('3770','Sawmills and wood preservation','Industry CDC Census 2010'),
   ('6280','Scenic and sightseeing transportation','Industry CDC Census 2010'),
   ('7460','Scientific research and development services','Industry CDC Census 2010'),
   ('1280','Seafood and other miscellaneous foods, n.e.c.','Industry CDC Census 2010'),
   ('6970','Securities, commodities, funds, trusts, and other financial investments','Industry CDC Census 2010'),
   ('6290','Services incidental to transportation','Industry CDC Census 2010'),
   ('7690','Services to buildings and dwellings (except cleaning during construction  and immediately after construction)','Industry CDC Census 2010'),
   ('0680','Sewage treatment facilities','Industry CDC Census 2010'),
   ('5280','Sewing, needlework, and piece goods stores','Industry CDC Census 2010'),
   ('3680','Ship and boat building','Industry CDC Census 2010'),
   ('5180','Shoe stores','Industry CDC Census 2010'),
   ('2280','Soap, cleaning compound, and cosmetics manufacturing','Industry CDC Census 2010'),
   ('6490','Software publishers','Industry CDC Census 2010'),
   ('6590','Sound recording industries','Industry CDC Census 2010'),
   ('7370','Specialized design services','Industry CDC Census 2010'),
   ('4980','Specialty food stores','Industry CDC Census 2010'),
   ('3970','Sporting and athletic goods, and doll, toy and game manufacturing','Industry CDC Census 2010'),
   ('5270','Sporting goods, camera, and hobby and toy stores','Industry CDC Census 2010'),
   ('2480','Structural clay product manufacturing','Industry CDC Census 2010'),
   ('2870','Structural metals, and boiler, tank, and shipping container manufacturing','Industry CDC Census 2010'),
   ('1080','Sugar and confectionery products','Industry CDC Census 2010'),
   ('0290','Support activities for agriculture and forestry','Industry CDC Census 2010'),
   ('0490','Support activities for mining','Industry CDC Census 2010'),
   ('6190','Taxi and limousine service','Industry CDC Census 2010'),
   ('1490','Textile and fabric finishing and coating mills','Industry CDC Census 2010'),
   ('1590','Textile product mills, except carpets and rugs','Industry CDC Census 2010'),
   ('2380','Tire manufacturing','Industry CDC Census 2010'),
   ('1390','Tobacco manufacturing','Industry CDC Census 2010'),
   ('7670','Travel arrangements and reservation services','Industry CDC Census 2010'),
   ('8660','Traveler accommodation','Industry CDC Census 2010'),
   ('6170','Truck transportation','Industry CDC Census 2010'),
   ('9670','U. S Army','Industry CDC Census 2010'),
   ('9680','U. S. Air Force','Industry CDC Census 2010'),
   ('9790','U. S. Armed Forces, Branch not specified','Industry CDC Census 2010'),
   ('9780','U. S. Coast Guard','Industry CDC Census 2010'),
   ('9770','U. S. Marines','Industry CDC Census 2010'),
   ('9690','U. S. Navy','Industry CDC Census 2010'),
   ('5490','Used merchandise stores','Industry CDC Census 2010'),
   ('5670','Vending machine operators','Industry CDC Census 2010'),
   ('3780','Veneer, plywood, and engineered wood products','Industry CDC Census 2010'),
   ('7480','Veterinary services','Industry CDC Census 2010'),
   ('7170','Video tape and disk rental','Industry CDC Census 2010'),
   ('8390','Vocational rehabilitation services','Industry CDC Census 2010'),
   ('6390','Warehousing and storage','Industry CDC Census 2010'),
   ('7790','Waste management and remediation services','Industry CDC Census 2010'),
   ('6090','Water transportation','Industry CDC Census 2010'),
   ('0670','Water, steam, air-conditioning, and irrigation systems','Industry CDC Census 2010'),
   ('4585','Wholesale electronic markets agents and brokers','Industry CDC Census 2010'),
   ('6680','Wired telecommunications carriers','Industry CDC Census 2010')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Industry_Code]
   SET Data_Owner_ID = 'CDC',
       Agency_Reporting_ID = 'Census',
       Version_Number = 'v1'
GO

-- Census Occupation v1
INSERT INTO [Entity].[Occupation_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('0800','Accountants and auditors','Occupation CDC Census 2010'),
   ('2700','Actors','Occupation CDC Census 2010'),
   ('1200','Actuaries','Occupation CDC Census 2010'),
   ('8850','Adhesive bonding machine operators and tenders','Occupation CDC Census 2010'),
   ('0100','Administrative services managers','Occupation CDC Census 2010'),
   ('0040','Advertising and promotions managers','Occupation CDC Census 2010'),
   ('4800','Advertising sales agents','Occupation CDC Census 2010'),
   ('1320','Aerospace engineers','Occupation CDC Census 2010'),
   ('0500','Agents and business managers of artists, performers, and athletes','Occupation CDC Census 2010'),
   ('1900','Agricultural and food science technicians','Occupation CDC Census 2010'),
   ('1600','Agricultural and food scientists','Occupation CDC Census 2010'),
   ('1330','Agricultural engineers','Occupation CDC Census 2010'),
   ('6010','Agricultural inspectors','Occupation CDC Census 2010'),
   ('9040','Air traffic controllers and airfield operations specialists','Occupation CDC Census 2010'),
   ('7140','Aircraft mechanics and service technicians','Occupation CDC Census 2010'),
   ('9030','Aircraft pilots and flight engineers','Occupation CDC Census 2010'),
   ('7710','Aircraft structure, surfaces, rigging, and systems assemblers','Occupation CDC Census 2010'),
   ('9110','Ambulance drivers and attendants, except emergency medical technicians','Occupation CDC Census 2010'),
   ('6020','Animal breeders','Occupation CDC Census 2010'),
   ('3900','Animal control workers','Occupation CDC Census 2010'),
   ('4340','Animal trainers','Occupation CDC Census 2010'),
   ('2800','Announcers','Occupation CDC Census 2010'),
   ('0810','Appraisers and assessors of real estate','Occupation CDC Census 2010'),
   ('1300','Architects, except naval','Occupation CDC Census 2010'),
   ('0300','Architectural and engineering managers','Occupation CDC Census 2010'),
   ('2400','Archivists, curators, and museum technicians','Occupation CDC Census 2010'),
   ('2600','Artists and related workers','Occupation CDC Census 2010'),
   ('1700','Astronomers and physicists','Occupation CDC Census 2010'),
   ('2720','Athletes, coaches, umpires, and related workers','Occupation CDC Census 2010'),
   ('1710','Atmospheric and space scientists','Occupation CDC Census 2010'),
   ('3140','Audiologists','Occupation CDC Census 2010'),
   ('9360','Automotive and watercraft service attendants','Occupation CDC Census 2010'),
   ('7150','Automotive body and related repairers','Occupation CDC Census 2010'),
   ('7160','Automotive glass installers and repairers','Occupation CDC Census 2010'),
   ('7200','Automotive service technicians and mechanics','Occupation CDC Census 2010'),
   ('7030','Avionics technicians','Occupation CDC Census 2010'),
   ('4530','Baggage porters, bellhops, and concierges','Occupation CDC Census 2010'),
   ('3800','Bailiffs, correctional officers, and jailers','Occupation CDC Census 2010'),
   ('7800','Bakers','Occupation CDC Census 2010'),
   ('4500','Barbers','Occupation CDC Census 2010'),
   ('4040','Bartenders','Occupation CDC Census 2010'),
   ('5100','Bill and account collectors','Occupation CDC Census 2010'),
   ('5110','Billing and posting clerks','Occupation CDC Census 2010'),
   ('1610','Biological scientists','Occupation CDC Census 2010'),
   ('1910','Biological technicians','Occupation CDC Census 2010'),
   ('1340','Biomedical engineers','Occupation CDC Census 2010'),
   ('6210','Boilermakers','Occupation CDC Census 2010'),
   ('5120','Bookkeeping, accounting, and auditing clerks','Occupation CDC Census 2010'),
   ('6220','Brickmasons, blockmasons, and stonemasons','Occupation CDC Census 2010'),
   ('9340','Bridge and lock tenders','Occupation CDC Census 2010'),
   ('2900','Broadcast and sound engineering technicians and radio operators','Occupation CDC Census 2010'),
   ('5200','Brokerage clerks','Occupation CDC Census 2010'),
   ('0820','Budget analysts','Occupation CDC Census 2010'),
   ('7210','Bus and truck mechanics and diesel engine specialists','Occupation CDC Census 2010'),
   ('9120','Bus drivers','Occupation CDC Census 2010'),
   ('0740','Business operations specialists, all other','Occupation CDC Census 2010'),
   ('7810','Butchers and other meat, poultry, and fish processing workers','Occupation CDC Census 2010'),
   ('0510','Buyers and purchasing agents, farm products','Occupation CDC Census 2010'),
   ('8500','Cabinetmakers and bench carpenters','Occupation CDC Census 2010'),
   ('5500','Cargo and freight agents','Occupation CDC Census 2010'),
   ('6230','Carpenters','Occupation CDC Census 2010'),
   ('6240','Carpet, floor, and tile installers and finishers','Occupation CDC Census 2010'),
   ('4720','Cashiers','Occupation CDC Census 2010'),
   ('6250','Cement masons, concrete finishers, and terrazzo workers','Occupation CDC Census 2010'),
   ('4000','Chefs and head cooks','Occupation CDC Census 2010'),
   ('1350','Chemical engineers','Occupation CDC Census 2010'),
   ('8640','Chemical processing machine setters, operators, and tenders','Occupation CDC Census 2010'),
   ('1920','Chemical technicians','Occupation CDC Census 2010'),
   ('1720','Chemists and materials scientists','Occupation CDC Census 2010'),
   ('0010','Chief executives','Occupation CDC Census 2010'),
   ('4600','Childcare workers','Occupation CDC Census 2010'),
   ('3000','Chiropractors','Occupation CDC Census 2010'),
   ('1360','Civil engineers','Occupation CDC Census 2010'),
   ('0540','Claims adjusters, appraisers, examiners, and investigators','Occupation CDC Census 2010'),
   ('9610','Cleaners of vehicles and equipment','Occupation CDC Census 2010'),
   ('8860','Cleaning, washing, and metal pickling equipment operators and tenders','Occupation CDC Census 2010'),
   ('2040','Clergy','Occupation CDC Census 2010'),
   ('3300','Clinical laboratory technologists and technicians','Occupation CDC Census 2010'),
   ('7510','Coin, vending, and amusement machine servicers and repairers','Occupation CDC Census 2010'),
   ('4050','Combined food preparation and serving workers, including fast food','Occupation CDC Census 2010'),
   ('7520','Commercial divers','Occupation CDC Census 2010'),
   ('5030','Communications equipment operators, all other','Occupation CDC Census 2010'),
   ('0135','Compensation and benefits managers','Occupation CDC Census 2010'),
   ('0640','Compensation, benefits, and job analysis specialists','Occupation CDC Census 2010'),
   ('0565','Compliance officers','Occupation CDC Census 2010'),
   ('1005','Computer and information research scientists','Occupation CDC Census 2010'),
   ('0110','Computer and information systems managers','Occupation CDC Census 2010'),
   ('7900','Computer control programmers and operators','Occupation CDC Census 2010'),
   ('1400','Computer hardware engineers','Occupation CDC Census 2010'),
   ('1106','Computer network architects','Occupation CDC Census 2010'),
   ('1107','Computer occupations, all other','Occupation CDC Census 2010'),
   ('5800','Computer operators','Occupation CDC Census 2010'),
   ('1010','Computer programmers','Occupation CDC Census 2010'),
   ('1050','Computer support specialists','Occupation CDC Census 2010'),
   ('1006','Computer systems analysts','Occupation CDC Census 2010'),
   ('7010','Computer, automated teller, and office machine repairers','Occupation CDC Census 2010'),
   ('1640','Conservation scientists and foresters','Occupation CDC Census 2010'),
   ('6660','Construction and building inspectors','Occupation CDC Census 2010'),
   ('6260','Construction laborers','Occupation CDC Census 2010'),
   ('0220','Construction managers','Occupation CDC Census 2010'),
   ('7300','Control and valve installers and repairers','Occupation CDC Census 2010'),
   ('9500','Conveyor operators and tenders','Occupation CDC Census 2010'),
   ('4020','Cooks','Occupation CDC Census 2010'),
   ('8900','Cooling and freezing equipment operators and tenders','Occupation CDC Census 2010'),
   ('5210','Correspondence clerks','Occupation CDC Census 2010'),
   ('0600','Cost estimators','Occupation CDC Census 2010'),
   ('2000','Counselors','Occupation CDC Census 2010'),
   ('4740','Counter and rental clerks','Occupation CDC Census 2010'),
   ('4060','Counter attendants, cafeteria, food concession, and coffee shop','Occupation CDC Census 2010'),
   ('5510','Couriers and messengers','Occupation CDC Census 2010'),
   ('5220','Court, municipal, and license clerks','Occupation CDC Census 2010'),
   ('9510','Crane and tower operators','Occupation CDC Census 2010'),
   ('0830','Credit analysts','Occupation CDC Census 2010'),
   ('5230','Credit authorizers, checkers, and clerks','Occupation CDC Census 2010'),
   ('0910','Credit counselors and loan officers','Occupation CDC Census 2010'),
   ('3940','Crossing guards','Occupation CDC Census 2010'),
   ('8650','Crushing, grinding, polishing, mixing, and blending workers','Occupation CDC Census 2010'),
   ('5240','Customer service representatives','Occupation CDC Census 2010'),
   ('8710','Cutting workers','Occupation CDC Census 2010'),
   ('7950','Cutting, punching, and press machine setters, operators, and tenders,  metal and plastic','Occupation CDC Census 2010'),
   ('2740','Dancers and choreographers','Occupation CDC Census 2010'),
   ('5810','Data entry keyers','Occupation CDC Census 2010'),
   ('1060','Database administrators','Occupation CDC Census 2010'),
   ('3640','Dental assistants','Occupation CDC Census 2010'),
   ('3310','Dental hygienists','Occupation CDC Census 2010'),
   ('3010','Dentists','Occupation CDC Census 2010'),
   ('6800','Derrick, rotary drill, and service unit operators, oil, gas, and mining','Occupation CDC Census 2010'),
   ('2630','Designers','Occupation CDC Census 2010'),
   ('5830','Desktop publishers','Occupation CDC Census 2010'),
   ('3820','Detectives and criminal investigators','Occupation CDC Census 2010'),
   ('3320','Diagnostic related technologists and technicians','Occupation CDC Census 2010'),
   ('3030','Dietitians and nutritionists','Occupation CDC Census 2010'),
   ('4130','Dining room and cafeteria attendants and bartender helpers','Occupation CDC Census 2010'),
   ('2050','Directors, religious activities and education','Occupation CDC Census 2010'),
   ('4140','Dishwashers','Occupation CDC Census 2010'),
   ('5520','Dispatchers','Occupation CDC Census 2010'),
   ('4950','Door-to-door sales workers, news and street vendors, and related workers','Occupation CDC Census 2010'),
   ('1540','Drafters','Occupation CDC Census 2010'),
   ('9520','Dredge, excavating, and loading machine operators','Occupation CDC Census 2010'),
   ('7960','Drilling and boring machine tool setters, operators, and tenders, metal  and plastic','Occupation CDC Census 2010'),
   ('9130','Driver/sales workers and truck drivers','Occupation CDC Census 2010'),
   ('6330','Drywall installers, ceiling tile installers, and tapers','Occupation CDC Census 2010'),
   ('6820','Earth drillers, except oil and gas','Occupation CDC Census 2010'),
   ('1800','Economists','Occupation CDC Census 2010'),
   ('2830','Editors','Occupation CDC Census 2010'),
   ('0230','Education administrators','Occupation CDC Census 2010'),
   ('7040','Electric motor, power tool, and related repairers','Occupation CDC Census 2010'),
   ('1410','Electrical and electronics engineers','Occupation CDC Census 2010'),
   ('7050','Electrical and electronics installers and repairers, transportation equipment','Occupation CDC Census 2010'),
   ('7100','Electrical and electronics repairers, industrial and utility','Occupation CDC Census 2010'),
   ('7410','Electrical power-line installers and repairers','Occupation CDC Census 2010'),
   ('7720','Electrical, electronics, and electromechanical assemblers','Occupation CDC Census 2010'),
   ('6355','Electricians','Occupation CDC Census 2010'),
   ('7110','Electronic equipment installers and repairers, motor vehicles','Occupation CDC Census 2010'),
   ('7120','Electronic home entertainment equipment installers and repairers','Occupation CDC Census 2010'),
   ('2310','Elementary and middle school teachers','Occupation CDC Census 2010'),
   ('6700','Elevator installers and repairers','Occupation CDC Census 2010'),
   ('5250','Eligibility interviewers, government programs','Occupation CDC Census 2010'),
   ('4460','Embalmers and funeral attendants','Occupation CDC Census 2010'),
   ('0425','Emergency management directors','Occupation CDC Census 2010'),
   ('3400','Emergency medical technicians and paramedics','Occupation CDC Census 2010'),
   ('7730','Engine and other machine assemblers','Occupation CDC Census 2010'),
   ('1550','Engineering technicians, except drafters','Occupation CDC Census 2010'),
   ('1530','Engineers, all other','Occupation CDC Census 2010'),
   ('2760','Entertainers and performers, sports and related workers, all other','Occupation CDC Census 2010'),
   ('1420','Environmental engineers','Occupation CDC Census 2010'),
   ('1740','Environmental scientists and geoscientists','Occupation CDC Census 2010'),
   ('8910','Etchers and engravers','Occupation CDC Census 2010'),
   ('3235','Exercise physiologists','Occupation CDC Census 2010'),
   ('6830','Explosives workers, ordnance handling experts, and blasters','Occupation CDC Census 2010'),
   ('7920','Extruding and drawing machine setters, operators, and tenders, metal and  plastic','Occupation CDC Census 2010'),
   ('8430','Extruding and forming machine setters, operators, and tenders, synthetic  and glass fibers','Occupation CDC Census 2010'),
   ('8720','Extruding, forming, pressing, and compacting machine setters, operators,  and tenders','Occupation CDC Census 2010'),
   ('8440','Fabric and apparel patternmakers','Occupation CDC Census 2010'),
   ('0205','Farmers, ranchers, and other agricultural managers','Occupation CDC Census 2010'),
   ('6710','Fence erectors','Occupation CDC Census 2010'),
   ('5260','File clerks','Occupation CDC Census 2010'),
   ('0840','Financial analysts','Occupation CDC Census 2010'),
   ('5165','Financial clerks, all other','Occupation CDC Census 2010'),
   ('0900','Financial examiners','Occupation CDC Census 2010'),
   ('0120','Financial managers','Occupation CDC Census 2010'),
   ('0950','Financial specialists, all other','Occupation CDC Census 2010'),
   ('3750','Fire inspectors','Occupation CDC Census 2010'),
   ('3740','Firefighters','Occupation CDC Census 2010'),
   ('6200','First-line supervisors of construction trades and extraction workers','Occupation CDC Census 2010'),
   ('3700','First-line supervisors of correctional officers','Occupation CDC Census 2010'),
   ('6005','First-line supervisors of farming, fishing, and forestry workers','Occupation CDC Census 2010'),
   ('3720','First-line supervisors of fire fighting and prevention workers','Occupation CDC Census 2010'),
   ('4010','First-line supervisors of food preparation and serving workers','Occupation CDC Census 2010'),
   ('4300','First-line supervisors of gaming workers','Occupation CDC Census 2010'),
   ('4200','First-line supervisors of housekeeping and janitorial workers','Occupation CDC Census 2010'),
   ('4210','First-line supervisors of landscaping, lawn service, and groundskeeping  workers','Occupation CDC Census 2010'),
   ('7000','First-line supervisors of mechanics, installers, and repairers','Occupation CDC Census 2010'),
   ('4710','First-line supervisors of non-retail sales workers','Occupation CDC Census 2010'),
   ('5000','First-line supervisors of office and administrative support workers','Occupation CDC Census 2010'),
   ('4320','First-line supervisors of personal service workers','Occupation CDC Census 2010'),
   ('3710','First-line supervisors of police and detectives','Occupation CDC Census 2010'),
   ('7700','First-line supervisors of production and operating workers','Occupation CDC Census 2010'),
   ('3730','First-line supervisors of protective service workers, all other','Occupation CDC Census 2010'),
   ('4700','First-line supervisors of retail sales workers','Occupation CDC Census 2010'),
   ('3830','Fish and game wardens','Occupation CDC Census 2010'),
   ('6100','Fishers and related fishing workers','Occupation CDC Census 2010'),
   ('9050','Flight attendants','Occupation CDC Census 2010'),
   ('7830','Food and tobacco roasting, baking, and drying machine operators and tenders','Occupation CDC Census 2010'),
   ('7840','Food batchmakers','Occupation CDC Census 2010'),
   ('7850','Food cooking machine operators and tenders','Occupation CDC Census 2010'),
   ('4160','Food preparation and serving related workers, all other','Occupation CDC Census 2010'),
   ('4030','Food preparation workers','Occupation CDC Census 2010'),
   ('7855','Food processing workers, all other','Occupation CDC Census 2010'),
   ('4120','Food servers, nonrestaurant','Occupation CDC Census 2010'),
   ('0310','Food service managers','Occupation CDC Census 2010'),
   ('6120','Forest and conservation workers','Occupation CDC Census 2010'),
   ('7930','Forging machine setters, operators, and tenders, metal and plastic','Occupation CDC Census 2010'),
   ('0726','Fundraisers','Occupation CDC Census 2010'),
   ('0325','Funeral service managers','Occupation CDC Census 2010'),
   ('8730','Furnace, kiln, oven, drier, and kettle operators and tenders','Occupation CDC Census 2010'),
   ('8510','Furniture finishers','Occupation CDC Census 2010'),
   ('5130','Gaming cage workers','Occupation CDC Census 2010'),
   ('0330','Gaming managers','Occupation CDC Census 2010'),
   ('4400','Gaming services workers','Occupation CDC Census 2010'),
   ('0020','General and operations managers','Occupation CDC Census 2010'),
   ('1930','Geological and petroleum technicians','Occupation CDC Census 2010'),
   ('6360','Glaziers','Occupation CDC Census 2010'),
   ('6040','Graders and sorters, agricultural products','Occupation CDC Census 2010'),
   ('8000','Grinding, lapping, polishing, and buffing machine tool setters, operators,  and tenders, metal and plastic','Occupation CDC Census 2010'),
   ('4250','Grounds maintenance workers','Occupation CDC Census 2010'),
   ('4510','Hairdressers, hairstylists, and cosmetologists','Occupation CDC Census 2010'),
   ('6720','Hazardous materials removal workers','Occupation CDC Census 2010'),
   ('3260','Health diagnosing and treating practitioners, all other','Occupation CDC Census 2010'),
   ('3420','Health practitioner support technologists and technicians','Occupation CDC Census 2010'),
   ('3655','Healthcare support workers, all other, including medical equipment preparers','Occupation CDC Census 2010'),
   ('8150','Heat treating equipment setters, operators, and tenders, metal and plastic','Occupation CDC Census 2010'),
   ('7315','Heating, air conditioning, and refrigeration mechanics and installers','Occupation CDC Census 2010'),
   ('7220','Heavy vehicle and mobile equipment service technicians and mechanics','Occupation CDC Census 2010'),
   ('6600','Helpers, construction trades','Occupation CDC Census 2010'),
   ('6930','Helpers--extraction workers','Occupation CDC Census 2010'),
   ('7610','Helpers--installation, maintenance, and repair workers','Occupation CDC Census 2010'),
   ('8950','Helpers--production workers','Occupation CDC Census 2010'),
   ('6730','Highway maintenance workers','Occupation CDC Census 2010'),
   ('9560','Hoist and winch operators','Occupation CDC Census 2010'),
   ('7320','Home appliance repairers','Occupation CDC Census 2010'),
   ('9010','Homemaker, Housewife - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('4150','Hosts and hostesses, restaurant, lounge, and coffee shop','Occupation CDC Census 2010'),
   ('5300','Hotel, motel, and resort desk clerks','Occupation CDC Census 2010'),
   ('5360','Human resources assistants, except payroll and timekeeping','Occupation CDC Census 2010'),
   ('0136','Human resources managers','Occupation CDC Census 2010'),
   ('0630','Human resources workers','Occupation CDC Census 2010'),
   ('6110','Hunters and trappers','Occupation CDC Census 2010'),
   ('7330','Industrial and refractory machinery mechanics','Occupation CDC Census 2010'),
   ('1430','Industrial engineers, including health and safety','Occupation CDC Census 2010'),
   ('0140','Industrial production managers','Occupation CDC Census 2010'),
   ('9600','Industrial truck and tractor operators','Occupation CDC Census 2010'),
   ('5420','Information and record clerks, all other','Occupation CDC Census 2010'),
   ('1007','Information security analysts','Occupation CDC Census 2010'),
   ('8740','Inspectors, testers, sorters, samplers, and weighers','Occupation CDC Census 2010'),
   ('6400','Insulation workers','Occupation CDC Census 2010'),
   ('5840','Insurance claims and policy processing clerks','Occupation CDC Census 2010'),
   ('4810','Insurance sales agents','Occupation CDC Census 2010'),
   ('0860','Insurance underwriters','Occupation CDC Census 2010'),
   ('5310','Interviewers, except eligibility and loan','Occupation CDC Census 2010'),
   ('4220','Janitors and building cleaners','Occupation CDC Census 2010'),
   ('8750','Jewelers and precious stone and metal workers','Occupation CDC Census 2010'),
   ('2110','Judges, magistrates, and other judicial workers','Occupation CDC Census 2010'),
   ('2105','Judicial law clerks','Occupation CDC Census 2010'),
   ('9620','Laborers and freight, stock, and material movers, hand','Occupation CDC Census 2010'),
   ('8010','Lathe and turning machine tool setters, operators, and tenders, metal  and plastic','Occupation CDC Census 2010'),
   ('8300','Laundry and dry-cleaning workers','Occupation CDC Census 2010'),
   ('2100','Lawyers','Occupation CDC Census 2010'),
   ('8160','Layout workers, metal and plastic','Occupation CDC Census 2010'),
   ('0030','Legislators','Occupation CDC Census 2010'),
   ('2430','Librarians','Occupation CDC Census 2010'),
   ('5320','Library assistants, clerical','Occupation CDC Census 2010'),
   ('2440','Library technicians','Occupation CDC Census 2010'),
   ('3500','Licensed practical and licensed vocational nurses','Occupation CDC Census 2010'),
   ('1660','Life scientists, all other','Occupation CDC Census 2010'),
   ('3955','Lifeguards and other recreational, and all other protective service workers','Occupation CDC Census 2010'),
   ('5330','Loan interviewers and clerks','Occupation CDC Census 2010'),
   ('7540','Locksmiths and safe repairers','Occupation CDC Census 2010'),
   ('9200','Locomotive engineers and operators','Occupation CDC Census 2010'),
   ('0340','Lodging managers','Occupation CDC Census 2010'),
   ('6130','Logging workers','Occupation CDC Census 2010'),
   ('0700','Logisticians','Occupation CDC Census 2010'),
   ('9630','Machine feeders and offbearers','Occupation CDC Census 2010'),
   ('8030','Machinists','Occupation CDC Census 2010'),
   ('4230','Maids and housekeeping cleaners','Occupation CDC Census 2010'),
   ('5850','Mail clerks and mail machine operators, except postal service','Occupation CDC Census 2010'),
   ('7340','Maintenance and repair workers, general','Occupation CDC Census 2010'),
   ('7350','Maintenance workers, machinery','Occupation CDC Census 2010'),
   ('0710','Management analysts','Occupation CDC Census 2010'),
   ('0430','Managers, all other','Occupation CDC Census 2010'),
   ('7550','Manufactured building and mobile home installers','Occupation CDC Census 2010'),
   ('1440','Marine engineers and naval architects','Occupation CDC Census 2010'),
   ('0735','Market research analysts and marketing specialists','Occupation CDC Census 2010'),
   ('0050','Marketing and sales managers','Occupation CDC Census 2010'),
   ('3630','Massage therapists','Occupation CDC Census 2010'),
   ('9750','Material moving workers, all other','Occupation CDC Census 2010'),
   ('1450','Materials engineers','Occupation CDC Census 2010'),
   ('1210','Mathematicians','Occupation CDC Census 2010'),
   ('1460','Mechanical engineers','Occupation CDC Census 2010'),
   ('2960','Media and communication equipment workers, all other','Occupation CDC Census 2010'),
   ('0350','Medical and health services managers','Occupation CDC Census 2010'),
   ('3645','Medical assistants','Occupation CDC Census 2010'),
   ('3510','Medical records and health information technicians','Occupation CDC Census 2010'),
   ('1650','Medical scientists','Occupation CDC Census 2010'),
   ('3646','Medical transcriptionists','Occupation CDC Census 2010'),
   ('8760','Medical, dental, and ophthalmic laboratory technicians','Occupation CDC Census 2010'),
   ('0725','Meeting, convention, and event planners','Occupation CDC Census 2010'),
   ('8040','Metal furnace operators, tenders, pourers, and casters','Occupation CDC Census 2010'),
   ('8220','Metal workers and plastic workers, all other','Occupation CDC Census 2010'),
   ('5530','Meter readers, utilities','Occupation CDC Census 2010'),
   ('9840','Military, Commissioned Officer - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('9850','Military, Non-commissioned Officer/Enlisted - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('9830','Military, rank not specified','Occupation CDC Census 2010'),
   ('8020','Milling and planing machine setters, operators, and tenders, metal and  plastic','Occupation CDC Census 2010'),
   ('7360','Millwrights','Occupation CDC Census 2010'),
   ('9730','Mine shuttle car operators','Occupation CDC Census 2010'),
   ('1500','Mining and geological engineers, including mining safety engineers','Occupation CDC Census 2010'),
   ('6840','Mining machine operators','Occupation CDC Census 2010'),
   ('6050','Miscellaneous agricultural workers','Occupation CDC Census 2010'),
   ('7750','Miscellaneous assemblers and fabricators','Occupation CDC Census 2010'),
   ('2025','Miscellaneous community and social service specialists, including health  educators and community health workers','Occupation CDC Census 2010'),
   ('6765','Miscellaneous construction and related workers','Occupation CDC Census 2010'),
   ('4430','Miscellaneous entertainment attendants and related workers','Occupation CDC Census 2010'),
   ('3535','Miscellaneous health technologists and technicians','Occupation CDC Census 2010'),
   ('2160','Miscellaneous legal support workers','Occupation CDC Census 2010'),
   ('1965','Miscellaneous life, physical, and social science technicians','Occupation CDC Census 2010'),
   ('1240','Miscellaneous mathematical science occupations','Occupation CDC Census 2010'),
   ('2860','Miscellaneous media and communication workers','Occupation CDC Census 2010'),
   ('4520','Miscellaneous personal appearance workers','Occupation CDC Census 2010'),
   ('8630','Miscellaneous plant and system operators','Occupation CDC Census 2010'),
   ('1860','Miscellaneous social scientists and related workers','Occupation CDC Census 2010'),
   ('7260','Miscellaneous vehicle and mobile equipment mechanics, installers, and  repairers','Occupation CDC Census 2010'),
   ('8060','Model makers and patternmakers, metal and plastic','Occupation CDC Census 2010'),
   ('8520','Model makers and patternmakers, wood','Occupation CDC Census 2010'),
   ('4900','Models, demonstrators, and product promoters','Occupation CDC Census 2010'),
   ('8100','Molders and molding machine setters, operators, and tenders, metal and  plastic','Occupation CDC Census 2010'),
   ('8920','Molders, shapers, and casters, except metal and plastic','Occupation CDC Census 2010'),
   ('4465','Morticians, undertakers, and funeral directors','Occupation CDC Census 2010'),
   ('4410','Motion picture projectionists','Occupation CDC Census 2010'),
   ('9150','Motor vehicle operators, all other','Occupation CDC Census 2010'),
   ('8120','Multiple machine tool setters, operators, and tenders, metal and plastic','Occupation CDC Census 2010'),
   ('2750','Musicians, singers, and related workers','Occupation CDC Census 2010'),
   ('0360','Natural sciences managers','Occupation CDC Census 2010'),
   ('1105','Network and computer systems administrators','Occupation CDC Census 2010'),
   ('9100','Never worked, disabled, child/infant - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('5340','New accounts clerks','Occupation CDC Census 2010'),
   ('2810','News analysts, reporters and correspondents','Occupation CDC Census 2010'),
   ('4350','Nonfarm animal caretakers','Occupation CDC Census 2010'),
   ('1510','Nuclear engineers','Occupation CDC Census 2010'),
   ('1940','Nuclear technicians','Occupation CDC Census 2010'),
   ('3256','Nurse anesthetists','Occupation CDC Census 2010'),
   ('3257','Nurse midwives','Occupation CDC Census 2010'),
   ('3258','Nurse practitioners','Occupation CDC Census 2010'),
   ('3600','Nursing, psychiatric, and home health aides','Occupation CDC Census 2010'),
   ('3150','Occupational therapists','Occupation CDC Census 2010'),
   ('3610','Occupational therapy assistants and aides','Occupation CDC Census 2010'),
   ('5940','Office and administrative support workers, all other','Occupation CDC Census 2010'),
   ('5860','Office clerks, general','Occupation CDC Census 2010'),
   ('5900','Office machine operators, except computer','Occupation CDC Census 2010'),
   ('6320','Operating engineers and other construction equipment operators','Occupation CDC Census 2010'),
   ('1220','Operations research analysts','Occupation CDC Census 2010'),
   ('3520','Opticians, dispensing','Occupation CDC Census 2010'),
   ('3040','Optometrists','Occupation CDC Census 2010'),
   ('5350','Order clerks','Occupation CDC Census 2010'),
   ('2550','Other education, training, and library workers','Occupation CDC Census 2010'),
   ('6940','Other extraction workers','Occupation CDC Census 2010'),
   ('3540','Other healthcare practitioners and technical occupations','Occupation CDC Census 2010'),
   ('7630','Other installation, maintenance, and repair workers','Occupation CDC Census 2010'),
   ('2340','Other teachers and instructors','Occupation CDC Census 2010'),
   ('9420','Other transportation workers','Occupation CDC Census 2010'),
   ('8800','Packaging and filling machine operators and tenders','Occupation CDC Census 2010'),
   ('9640','Packers and packagers, hand','Occupation CDC Census 2010'),
   ('6420','Painters, construction and maintenance','Occupation CDC Census 2010'),
   ('8810','Painting workers','Occupation CDC Census 2010'),
   ('8930','Paper goods machine setters, operators, and tenders','Occupation CDC Census 2010'),
   ('6430','Paperhangers','Occupation CDC Census 2010'),
   ('2145','Paralegals and legal assistants','Occupation CDC Census 2010'),
   ('3840','Parking enforcement workers','Occupation CDC Census 2010'),
   ('9350','Parking lot attendants','Occupation CDC Census 2010'),
   ('4750','Parts salespersons','Occupation CDC Census 2010'),
   ('6300','Paving, surfacing, and tamping equipment operators','Occupation CDC Census 2010'),
   ('5140','Payroll and timekeeping clerks','Occupation CDC Census 2010'),
   ('4610','Personal care aides','Occupation CDC Census 2010'),
   ('4650','Personal care and service workers, all other','Occupation CDC Census 2010'),
   ('0850','Personal financial advisors','Occupation CDC Census 2010'),
   ('4240','Pest control workers','Occupation CDC Census 2010'),
   ('1520','Petroleum engineers','Occupation CDC Census 2010'),
   ('3050','Pharmacists','Occupation CDC Census 2010'),
   ('3647','Pharmacy aides','Occupation CDC Census 2010'),
   ('3649','Phlebotomists','Occupation CDC Census 2010'),
   ('2910','Photographers','Occupation CDC Census 2010'),
   ('8830','Photographic process workers and processing machine operators','Occupation CDC Census 2010'),
   ('1760','Physical scientists, all other','Occupation CDC Census 2010'),
   ('3620','Physical therapist assistants and aides','Occupation CDC Census 2010'),
   ('3160','Physical therapists','Occupation CDC Census 2010'),
   ('3110','Physician assistants','Occupation CDC Census 2010'),
   ('3060','Physicians and surgeons','Occupation CDC Census 2010'),
   ('6310','Pile-driver operators','Occupation CDC Census 2010'),
   ('6440','Pipelayers, plumbers, pipefitters, and steamfitters','Occupation CDC Census 2010'),
   ('6460','Plasterers and stucco masons','Occupation CDC Census 2010'),
   ('8200','Plating and coating machine setters, operators, and tenders, metal and  plastic','Occupation CDC Census 2010'),
   ('3120','Podiatrists','Occupation CDC Census 2010'),
   ('3850','Police and sheriff''s patrol officers','Occupation CDC Census 2010'),
   ('5540','Postal service clerks','Occupation CDC Census 2010'),
   ('5550','Postal service mail carriers','Occupation CDC Census 2010'),
   ('5560','Postal service mail sorters, processors, and processing machine operators','Occupation CDC Census 2010'),
   ('0400','Postmasters and mail superintendents','Occupation CDC Census 2010'),
   ('2200','Postsecondary teachers','Occupation CDC Census 2010'),
   ('8600','Power plant operators, distributors, and dispatchers','Occupation CDC Census 2010'),
   ('7430','Precision instrument and equipment repairers','Occupation CDC Census 2010'),
   ('8250','Prepress technicians and workers','Occupation CDC Census 2010'),
   ('2300','Preschool and kindergarten teachers','Occupation CDC Census 2010'),
   ('8310','Pressers, textile, garment, and related materials','Occupation CDC Census 2010'),
   ('8256','Print binding and finishing workers','Occupation CDC Census 2010'),
   ('8255','Printing press operators','Occupation CDC Census 2010'),
   ('3910','Private detectives and investigators','Occupation CDC Census 2010'),
   ('2015','Probation officers and correctional treatment specialists','Occupation CDC Census 2010'),
   ('5150','Procurement clerks','Occupation CDC Census 2010'),
   ('2710','Producers and directors','Occupation CDC Census 2010'),
   ('8965','Production workers, all other','Occupation CDC Census 2010'),
   ('5600','Production, planning, and expediting clerks','Occupation CDC Census 2010'),
   ('5910','Proofreaders and copy markers','Occupation CDC Census 2010'),
   ('0410','Property, real estate, and community association managers','Occupation CDC Census 2010'),
   ('1820','Psychologists','Occupation CDC Census 2010'),
   ('0060','Public relations and fundraising managers','Occupation CDC Census 2010'),
   ('2825','Public relations specialists','Occupation CDC Census 2010'),
   ('9650','Pumping station operators','Occupation CDC Census 2010'),
   ('0530','Purchasing agents, except wholesale, retail, and farm products','Occupation CDC Census 2010'),
   ('0150','Purchasing managers','Occupation CDC Census 2010'),
   ('3200','Radiation therapists','Occupation CDC Census 2010'),
   ('7020','Radio and telecommunications equipment installers and repairers','Occupation CDC Census 2010'),
   ('9230','Railroad brake, signal, and switch operators','Occupation CDC Census 2010'),
   ('9240','Railroad conductors and yardmasters','Occupation CDC Census 2010'),
   ('6740','Rail-track laying and maintenance equipment operators','Occupation CDC Census 2010'),
   ('4920','Real estate brokers and sales agents','Occupation CDC Census 2010'),
   ('5400','Receptionists and information clerks','Occupation CDC Census 2010'),
   ('4620','Recreation and fitness workers','Occupation CDC Census 2010'),
   ('3210','Recreational therapists','Occupation CDC Census 2010'),
   ('9720','Refuse and recyclable material collectors','Occupation CDC Census 2010'),
   ('3255','Registered nurses','Occupation CDC Census 2010'),
   ('6500','Reinforcing iron and rebar workers','Occupation CDC Census 2010'),
   ('2060','Religious workers, all other','Occupation CDC Census 2010'),
   ('5410','Reservation and transportation ticket agents and travel clerks','Occupation CDC Census 2010'),
   ('4640','Residential advisors','Occupation CDC Census 2010'),
   ('3220','Respiratory therapists','Occupation CDC Census 2010'),
   ('4760','Retail salespersons','Occupation CDC Census 2010'),
   ('9060','Retired - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('7560','Riggers','Occupation CDC Census 2010'),
   ('7940','Rolling machine setters, operators, and tenders, metal and plastic','Occupation CDC Census 2010'),
   ('6910','Roof bolters, mining','Occupation CDC Census 2010'),
   ('6515','Roofers','Occupation CDC Census 2010'),
   ('6920','Roustabouts, oil and gas','Occupation CDC Census 2010'),
   ('9300','Sailors and marine oilers','Occupation CDC Census 2010'),
   ('4965','Sales and related workers, all other','Occupation CDC Census 2010'),
   ('4930','Sales engineers','Occupation CDC Census 2010'),
   ('4840','Sales representatives, services, all other','Occupation CDC Census 2010'),
   ('4850','Sales representatives, wholesale and manufacturing','Occupation CDC Census 2010'),
   ('8530','Sawing machine setters, operators, and tenders, wood','Occupation CDC Census 2010'),
   ('2320','Secondary school teachers','Occupation CDC Census 2010'),
   ('5700','Secretaries and administrative assistants','Occupation CDC Census 2010'),
   ('4820','Securities, commodities, and financial services sales agents','Occupation CDC Census 2010'),
   ('7130','Security and fire alarm systems installers','Occupation CDC Census 2010'),
   ('3930','Security guards and gaming surveillance officers','Occupation CDC Census 2010'),
   ('8840','Semiconductor processors','Occupation CDC Census 2010'),
   ('6750','Septic tank servicers and sewer pipe cleaners','Occupation CDC Census 2010'),
   ('8320','Sewing machine operators','Occupation CDC Census 2010'),
   ('6520','Sheet metal workers','Occupation CDC Census 2010'),
   ('9310','Ship and boat captains and operators','Occupation CDC Census 2010'),
   ('9330','Ship engineers','Occupation CDC Census 2010'),
   ('5610','Shipping, receiving, and traffic clerks','Occupation CDC Census 2010'),
   ('8330','Shoe and leather workers and repairers','Occupation CDC Census 2010'),
   ('8340','Shoe machine operators and tenders','Occupation CDC Census 2010'),
   ('7600','Signal and track switch repairers','Occupation CDC Census 2010'),
   ('7240','Small engine mechanics','Occupation CDC Census 2010'),
   ('0420','Social and community service managers','Occupation CDC Census 2010'),
   ('2016','Social and human service assistants','Occupation CDC Census 2010'),
   ('1950','Social science research assistants','Occupation CDC Census 2010'),
   ('2010','Social workers','Occupation CDC Census 2010'),
   ('1830','Sociologists','Occupation CDC Census 2010'),
   ('1020','Software developers, applications and systems software','Occupation CDC Census 2010'),
   ('6540','Solar photovoltaic installers','Occupation CDC Census 2010'),
   ('2330','Special education teachers','Occupation CDC Census 2010'),
   ('3230','Speech-language pathologists','Occupation CDC Census 2010'),
   ('8610','Stationary engineers and boiler operators','Occupation CDC Census 2010'),
   ('5920','Statistical assistants','Occupation CDC Census 2010'),
   ('1230','Statisticians','Occupation CDC Census 2010'),
   ('5620','Stock clerks and order fillers','Occupation CDC Census 2010'),
   ('6530','Structural iron and steel workers','Occupation CDC Census 2010'),
   ('7740','Structural metal fabricators and fitters','Occupation CDC Census 2010'),
   ('9070','Student - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('9260','Subway, streetcar, and other rail transportation workers','Occupation CDC Census 2010'),
   ('9000','Supervisors of transportation and material moving workers','Occupation CDC Census 2010'),
   ('1815','Survey researchers','Occupation CDC Census 2010'),
   ('1560','Surveying and mapping technicians','Occupation CDC Census 2010'),
   ('1310','Surveyors, cartographers, and photogrammetrists','Occupation CDC Census 2010'),
   ('5010','Switchboard operators, including answering service','Occupation CDC Census 2010'),
   ('8350','Tailors, dressmakers, and sewers','Occupation CDC Census 2010'),
   ('9740','Tank car, truck, and ship loaders','Occupation CDC Census 2010'),
   ('0930','Tax examiners and collectors, and revenue agents','Occupation CDC Census 2010'),
   ('0940','Tax preparers','Occupation CDC Census 2010'),
   ('9140','Taxi drivers and chauffeurs','Occupation CDC Census 2010'),
   ('2540','Teacher assistants','Occupation CDC Census 2010'),
   ('2840','Technical writers','Occupation CDC Census 2010'),
   ('7420','Telecommunications line installers and repairers','Occupation CDC Census 2010'),
   ('4940','Telemarketers','Occupation CDC Census 2010'),
   ('5020','Telephone operators','Occupation CDC Census 2010'),
   ('2920','Television, video, and motion picture camera operators and editors','Occupation CDC Census 2010'),
   ('5160','Tellers','Occupation CDC Census 2010'),
   ('8360','Textile bleaching and dyeing machine operators and tenders','Occupation CDC Census 2010'),
   ('8400','Textile cutting machine setters, operators, and tenders','Occupation CDC Census 2010'),
   ('8410','Textile knitting and weaving machine setters, operators, and tenders','Occupation CDC Census 2010'),
   ('8420','Textile winding, twisting, and drawing out machine setters, operators,  and tenders','Occupation CDC Census 2010'),
   ('8460','Textile, apparel, and furnishings workers, all other','Occupation CDC Census 2010'),
   ('3245','Therapists, all other','Occupation CDC Census 2010'),
   ('8940','Tire builders','Occupation CDC Census 2010'),
   ('8130','Tool and die makers','Occupation CDC Census 2010'),
   ('8210','Tool grinders, filers, and sharpeners','Occupation CDC Census 2010'),
   ('4540','Tour and travel guides','Occupation CDC Census 2010'),
   ('0137','Training and development managers','Occupation CDC Census 2010'),
   ('0650','Training and development specialists','Occupation CDC Census 2010'),
   ('3860','Transit and railroad police','Occupation CDC Census 2010'),
   ('9415','Transportation attendants, except flight attendants','Occupation CDC Census 2010'),
   ('9410','Transportation inspectors','Occupation CDC Census 2010'),
   ('3945','Transportation security screeners','Occupation CDC Census 2010'),
   ('0160','Transportation, storage, and distribution managers','Occupation CDC Census 2010'),
   ('4830','Travel agents','Occupation CDC Census 2010'),
   ('9900','Unemployed or Insufficient Information - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('8450','Upholsterers','Occupation CDC Census 2010'),
   ('1840','Urban and regional planners','Occupation CDC Census 2010'),
   ('4420','Ushers, lobby attendants, and ticket takers','Occupation CDC Census 2010'),
   ('3250','Veterinarians','Occupation CDC Census 2010'),
   ('3648','Veterinary assistants and laboratory animal caretakers','Occupation CDC Census 2010'),
   ('9020','Volunteer - NIOSH/NCHS','Occupation CDC Census 2010'),
   ('4110','Waiters and waitresses','Occupation CDC Census 2010'),
   ('8620','Water and wastewater treatment plant and system operators','Occupation CDC Census 2010'),
   ('1030','Web developers','Occupation CDC Census 2010'),
   ('5630','Weighers, measurers, checkers, and samplers, recordkeeping','Occupation CDC Census 2010'),
   ('8140','Welding, soldering, and brazing workers','Occupation CDC Census 2010'),
   ('0520','Wholesale and retail buyers, except farm products','Occupation CDC Census 2010'),
   ('7440','Wind turbine service technicians','Occupation CDC Census 2010'),
   ('8550','Woodworkers, all other','Occupation CDC Census 2010'),
   ('8540','Woodworking machine setters, operators, and tenders, except sawing','Occupation CDC Census 2010'),
   ('5820','Word processors and typists','Occupation CDC Census 2010'),
   ('2850','Writers and authors','Occupation CDC Census 2010')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Occupation_Code]
   SET Data_Owner_ID = 'CDC',
       Agency_Reporting_ID = 'Census',
       Version_Number = 'v1'
GO

-- Marital Status Code HL7 v1
INSERT INTO [Entity].[Marital_Status_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('N','Annulled','Marital status (HL7)'),
   ('C','Common law','Marital status (HL7)'),
   ('D','Divorced','Marital status (HL7)'),
   ('P','Domestic partner','Marital status (HL7)'),
   ('I','Interlocutory','Marital status (HL7)'),
   ('E','Legally Separated','Marital status (HL7)'),
   ('G','Living together','Marital status (HL7)'),
   ('M','Married','Marital status (HL7)'),
   ('O','Other','Marital status (HL7)'),
   ('R','Registered domestic partner','Marital status (HL7)'),
   ('A','Separated','Marital status (HL7)'),
   ('S','Single','Marital status (HL7)'),
   ('U','Unknown','Marital status (HL7)'),
   ('B','Unmarried','Marital status (HL7)'),
   ('T','Unreported','Marital status (HL7)'),
   ('W','Widowed','Marital status (HL7)')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Marital_Status_Code]
   SET Data_Owner_ID = 'HL7',
       Agency_Reporting_ID = 'HL7',
       Version_Number = 'v1'
GO

-- Indicator Flag Code
INSERT INTO [Entity].[Indicator_Flag_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('Y','Yes','INDICATOR-FLAG'),
   ('N','No','INDICATOR-FLAG'),
   ('U','Unknown','INDICATOR-FLAG')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Indicator_Flag_Code]
   SET Data_Owner_ID = 'COMMON',
       Agency_Reporting_ID = 'COMMON',
       Version_Number = 'v1'
GO

INSERT INTO [Entity].[Smoking_Status_Code] ([Code_ID], [Description], [CodeSet_Name]) VALUES
   ('428041000124106',	 'Current some day smoker',	                   'SNOMED-CT'),
   ('8517006',	          'Ex-smoker (finding)',	                         'SNOMED-CT'),
   ('266919005',	       'Never smoked tobacco (finding)',	             'SNOMED-CT'),
   ('77176002',	       'Smoker finding',	                            'SNOMED-CT'),
   ('449868002',	       'Smokes tobacco daily (finding)',	             'SNOMED-CT'),
   ('266927001',	       'Tobacco smoking consumption (unknown finding)','SNOMED-CT')
GO

-- update this so we know where the code came from...
UPDATE [Entity].[Indicator_Flag_Code]
   SET Data_Owner_ID = 'SNOMED-CT',
       Agency_Reporting_ID = 'SNOMED-CT',
       Version_Number = 'v1'
GO
