
-- Provider Codes NUCC v5

/*
The Healthcare Provider Taxonomy code set divides health care providers into 
hierarchical groupings by type, classification, and specialization, and assigns 
a code to each grouping. The Taxonomy consists of two parts: individuals 
(e.g., physicians) and non-individuals (e.g., ambulatory health care facilities). 
All codes are alphanumeric and are 10 positions in length. These codes are not 
“assigned” to health care providers; rather, health care providers select the 
taxonomy code(s) that most closely represents their education, license, 
or certification. If a health care provider has more than one taxonomy code 
associated with it, a health plan may prefer that the health care provider 
use one over another when submitting claims for certain services.
 */

INSERT INTO [Provider].[Provider_Code] ([Type_ID], [Description], [CodeSet_Name]) VALUES
   ('171100000X','Acupuncturist','NUCC Provider Codes'),
   ('372600000X','Adult Companion','NUCC Provider Codes'),
   ('125K00000X','Advanced Practice Dental Therapist','NUCC Provider Codes'),
   ('367A00000X','Advanced Practice Midwife','NUCC Provider Codes'),
   ('344800000X','Air Carrier','NUCC Provider Codes'),
   ('207K00000X','Allergy & Immunology','NUCC Provider Codes'),
   ('207KI0005X','Allergy & Immunology [Clinical & Laboratory Immunology]','NUCC Provider Codes'),
   ('207KA0200X','Allergy & Immunology [Allergy]','NUCC Provider Codes'),
   ('311500000X','Alzheimer Center (Dementia Center)','NUCC Provider Codes'),
   ('3416S0300X','Ambulance [Water Transport]','NUCC Provider Codes'),
   ('341600000X','Ambulance','NUCC Provider Codes'),
   ('3416L0300X','Ambulance [Land Transport]','NUCC Provider Codes'),
   ('3416A0800X','Ambulance [Air Transport]','NUCC Provider Codes'),
   ('229N00000X','Anaplastologist','NUCC Provider Codes'),
   ('367H00000X','Anesthesiologist Assistant','NUCC Provider Codes'),
   ('207LA0401X','Anesthesiology [Addiction Medicine]','NUCC Provider Codes'),
   ('207L00000X','Anesthesiology','NUCC Provider Codes'),
   ('207LP3000X','Anesthesiology [Pediatric Anesthesiology]','NUCC Provider Codes'),
   ('207LH0002X','Anesthesiology [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('207LP2900X','Anesthesiology [Pain Medicine]','NUCC Provider Codes'),
   ('207LC0200X','Anesthesiology [Critical Care Medicine]','NUCC Provider Codes'),
   ('221700000X','Art Therapist','NUCC Provider Codes'),
   ('106E00000X','Assistant Behavior Analyst','NUCC Provider Codes'),
   ('211D00000X','Assistant, Podiatric','NUCC Provider Codes'),
   ('3104A0625X','Assisted Living Facility [Assisted Living, Mental Illness]','NUCC Provider Codes'),
   ('310400000X','Assisted Living Facility','NUCC Provider Codes'),
   ('3104A0630X','Assisted Living Facility [Assisted Living, Behavioral Disturbances]','NUCC Provider Codes'),
   ('231H00000X','Audiologist','NUCC Provider Codes'),
   ('231HA2400X','Audiologist [Assistive Technology Practitioner]','NUCC Provider Codes'),
   ('231HA2500X','Audiologist [Assistive Technology Supplier]','NUCC Provider Codes'),
   ('237600000X','Audiologist-Hearing Aid Fitter','NUCC Provider Codes'),
   ('103K00000X','Behavior Analyst','NUCC Provider Codes'),
   ('106S00000X','Behavior Technician','NUCC Provider Codes'),
   ('331L00000X','Blood Bank','NUCC Provider Codes'),
   ('347B00000X','Bus','NUCC Provider Codes'),
   ('251B00000X','Case Management','NUCC Provider Codes'),
   ('171M00000X','Case Manager/Care Coordinator','NUCC Provider Codes'),
   ('111NS0005X','Chiropractor [Sports Physician]','NUCC Provider Codes'),
   ('111NP0017X','Chiropractor [Pediatric Chiropractor]','NUCC Provider Codes'),
   ('111NT0100X','Chiropractor [Thermography]','NUCC Provider Codes'),
   ('111NN1001X','Chiropractor [Nutrition]','NUCC Provider Codes'),
   ('111N00000X','Chiropractor','NUCC Provider Codes'),
   ('111NX0800X','Chiropractor [Orthopedic]','NUCC Provider Codes'),
   ('111NX0100X','Chiropractor [Occupational Health]','NUCC Provider Codes'),
   ('111NR0400X','Chiropractor [Rehabilitation]','NUCC Provider Codes'),
   ('111NN0400X','Chiropractor [Neurology]','NUCC Provider Codes'),
   ('111NI0900X','Chiropractor [Internist]','NUCC Provider Codes'),
   ('111NI0013X','Chiropractor [Independent Medical Examiner]','NUCC Provider Codes'),
   ('111NR0200X','Chiropractor [Radiology]','NUCC Provider Codes'),
   ('372500000X','Chore Provider','NUCC Provider Codes'),
   ('317400000X','Christian Science Facility','NUCC Provider Codes'),
   ('287300000X','Christian Science Sanitorium','NUCC Provider Codes'),
   ('281PC2000X','Chronic Disease Hospital [Children]','NUCC Provider Codes'),
   ('281P00000X','Chronic Disease Hospital','NUCC Provider Codes'),
   ('261QF0400X','Clinic/Center [Federally Qualified Health Center (FQHC)]','NUCC Provider Codes'),
   ('261QE0800X','Clinic/Center [Endoscopy]','NUCC Provider Codes'),
   ('261QG0250X','Clinic/Center [Genetics]','NUCC Provider Codes'),
   ('261QA3000X','Clinic/Center [Augmentative Communication]','NUCC Provider Codes'),
   ('261QU0200X','Clinic/Center [Urgent Care]','NUCC Provider Codes'),
   ('261QR0400X','Clinic/Center [Rehabilitation]','NUCC Provider Codes'),
   ('261QR0208X','Clinic/Center [Radiology, Mobile]','NUCC Provider Codes'),
   ('261QD0000X','Clinic/Center [Dental]','NUCC Provider Codes'),
   ('261QP2300X','Clinic/Center [Primary Care]','NUCC Provider Codes'),
   ('261QA0006X','Clinic/Center [Ambulatory Fertility Facility]','NUCC Provider Codes'),
   ('261QR0207X','Clinic/Center [Radiology, Mobile Mammography]','NUCC Provider Codes'),
   ('261QP0905X','Clinic/Center [Public Health, State or Local]','NUCC Provider Codes'),
   ('261QR0401X','Clinic/Center [Rehabilitation, Comprehensive Outpatient Rehabilitation  Facility (CORF)]','NUCC Provider Codes'),
   ('261QI0500X','Clinic/Center [Infusion Therapy]','NUCC Provider Codes'),
   ('261QM1000X','Clinic/Center [Migrant Health]','NUCC Provider Codes'),
   ('261QM1300X','Clinic/Center [Multi-Specialty]','NUCC Provider Codes'),
   ('261QR0404X','Clinic/Center [Rehabilitation, Cardiac Facilities]','NUCC Provider Codes'),
   ('261QH0700X','Clinic/Center [Hearing and Speech]','NUCC Provider Codes'),
   ('261QD1600X','Clinic/Center [Developmental Disabilities]','NUCC Provider Codes'),
   ('261QV0200X','Clinic/Center [VA]','NUCC Provider Codes'),
   ('261QM1100X','Clinic/Center [Military/U.S. Coast Guard Outpatient]','NUCC Provider Codes'),
   ('261QR0405X','Clinic/Center [Rehabilitation, Substance Use Disorder]','NUCC Provider Codes'),
   ('261QM3000X','Clinic/Center [Medically Fragile Infants and Children Day Care]','NUCC Provider Codes'),
   ('261QS1000X','Clinic/Center [Student Health]','NUCC Provider Codes'),
   ('261QX0100X','Clinic/Center [Occupational Medicine]','NUCC Provider Codes'),
   ('261QR0800X','Clinic/Center [Recovery Care]','NUCC Provider Codes'),
   ('261QM2800X','Clinic/Center [Methadone]','NUCC Provider Codes'),
   ('261QA1903X','Clinic/Center [Ambulatory Surgical]','NUCC Provider Codes'),
   ('261QX0200X','Clinic/Center [Oncology]','NUCC Provider Codes'),
   ('261QM1101X','Clinic/Center [Military and U.S. Coast Guard Ambulatory Procedure]','NUCC Provider Codes'),
   ('261QA0900X','Clinic/Center [Amputee]','NUCC Provider Codes'),
   ('261QL0400X','Clinic/Center [Lithotripsy]','NUCC Provider Codes'),
   ('261QS1200X','Clinic/Center [Sleep Disorder Diagnostic]','NUCC Provider Codes'),
   ('261QA0600X','Clinic/Center [Adult Day Care]','NUCC Provider Codes'),
   ('261QA0005X','Clinic/Center [Ambulatory Family Planning Facility]','NUCC Provider Codes'),
   ('261QC1800X','Clinic/Center [Corporate Health]','NUCC Provider Codes'),
   ('261QM0850X','Clinic/Center [Adult Mental Health]','NUCC Provider Codes'),
   ('261QM0801X','Clinic/Center [Mental Health (Including Community Mental Health Center)]','NUCC Provider Codes'),
   ('261QE0700X','Clinic/Center [End-Stage Renal Disease (ESRD) Treatment]','NUCC Provider Codes'),
   ('261QP1100X','Clinic/Center [Podiatric]','NUCC Provider Codes'),
   ('261QM1200X','Clinic/Center [Magnetic Resonance Imaging (MRI)]','NUCC Provider Codes'),
   ('261QB0400X','Clinic/Center [Birthing]','NUCC Provider Codes'),
   ('261QS0132X','Clinic/Center [Ophthalmologic Surgery]','NUCC Provider Codes'),
   ('261QH0100X','Clinic/Center [Health Service]','NUCC Provider Codes'),
   ('261QX0203X','Clinic/Center [Oncology, Radiation]','NUCC Provider Codes'),
   ('261QM2500X','Clinic/Center [Medical Specialty]','NUCC Provider Codes'),
   ('261QE0002X','Clinic/Center [Emergency Care]','NUCC Provider Codes'),
   ('261QR1100X','Clinic/Center [Research]','NUCC Provider Codes'),
   ('261QR1300X','Clinic/Center [Rural Health]','NUCC Provider Codes'),
   ('261QC0050X','Clinic/Center [Critical Access Hospital]','NUCC Provider Codes'),
   ('261QM1103X','Clinic/Center [Military Ambulatory Procedure Visits Operational (Transportable)]','NUCC Provider Codes'),
   ('261QR0200X','Clinic/Center [Radiology]','NUCC Provider Codes'),
   ('261QC1500X','Clinic/Center [Community Health]','NUCC Provider Codes'),
   ('261Q00000X','Clinic/Center','NUCC Provider Codes'),
   ('261QP2000X','Clinic/Center [Physical Therapy]','NUCC Provider Codes'),
   ('261QS0112X','Clinic/Center [Oral and Maxillofacial Surgery]','NUCC Provider Codes'),
   ('261QM1102X','Clinic/Center [Military Outpatient Operational (Transportable) Component]','NUCC Provider Codes'),
   ('261QM0855X','Clinic/Center [Adolescent and Children Mental Health]','NUCC Provider Codes'),
   ('261QR0206X','Clinic/Center [Radiology, Mammography]','NUCC Provider Codes'),
   ('261QF0050X','Clinic/Center [Family Planning, Non-Surgical]','NUCC Provider Codes'),
   ('261QP3300X','Clinic/Center [Pain]','NUCC Provider Codes'),
   ('261QP2400X','Clinic/Center [Prison Health]','NUCC Provider Codes'),
   ('261QP0904X','Clinic/Center [Public Health, Federal]','NUCC Provider Codes'),
   ('174V00000X','Clinical Ethicist','NUCC Provider Codes'),
   ('224Y00000X','Clinical Exercise Physiologist','NUCC Provider Codes'),
   ('291U00000X','Clinical Medical Laboratory','NUCC Provider Codes'),
   ('103GC0700X','Clinical Neuropsychologist [Clinical]','NUCC Provider Codes'),
   ('103G00000X','Clinical Neuropsychologist','NUCC Provider Codes'),
   ('364S00000X','Clinical Nurse Specialist','NUCC Provider Codes'),
   ('364SE1400X','Clinical Nurse Specialist [Ethics]','NUCC Provider Codes'),
   ('364SP0813X','Clinical Nurse Specialist [Psychiatric/Mental Health, Geropsychiatric]','NUCC Provider Codes'),
   ('364SW0102X','Clinical Nurse Specialist [Women''s Health]','NUCC Provider Codes'),
   ('364SM0705X','Clinical Nurse Specialist [Medical-Surgical]','NUCC Provider Codes'),
   ('364ST0500X','Clinical Nurse Specialist [Transplantation]','NUCC Provider Codes'),
   ('364SH1100X','Clinical Nurse Specialist [Holistic]','NUCC Provider Codes'),
   ('364SL0600X','Clinical Nurse Specialist [Long-Term Care]','NUCC Provider Codes'),
   ('364SP0811X','Clinical Nurse Specialist [Psychiatric/Mental Health, Chronically Ill]','NUCC Provider Codes'),
   ('364SG0600X','Clinical Nurse Specialist [Gerontology]','NUCC Provider Codes'),
   ('364SN0000X','Clinical Nurse Specialist [Neonatal]','NUCC Provider Codes'),
   ('364SN0800X','Clinical Nurse Specialist [Neuroscience]','NUCC Provider Codes'),
   ('364SP0200X','Clinical Nurse Specialist [Pediatrics]','NUCC Provider Codes'),
   ('364SE0003X','Clinical Nurse Specialist [Emergency]','NUCC Provider Codes'),
   ('364SX0200X','Clinical Nurse Specialist [Oncology]','NUCC Provider Codes'),
   ('364SP0812X','Clinical Nurse Specialist [Psychiatric/Mental Health, Community]','NUCC Provider Codes'),
   ('364SP2800X','Clinical Nurse Specialist [Perioperative]','NUCC Provider Codes'),
   ('364SP0810X','Clinical Nurse Specialist [Psychiatric/Mental Health, Child & Family]','NUCC Provider Codes'),
   ('364SC1501X','Clinical Nurse Specialist [Community Health/Public Health]','NUCC Provider Codes'),
   ('364SR0400X','Clinical Nurse Specialist [Rehabilitation]','NUCC Provider Codes'),
   ('364SP0808X','Clinical Nurse Specialist [Psychiatric/Mental Health]','NUCC Provider Codes'),
   ('364SX0204X','Clinical Nurse Specialist [Oncology, Pediatrics]','NUCC Provider Codes'),
   ('364SH0200X','Clinical Nurse Specialist [Home Health]','NUCC Provider Codes'),
   ('364SC2300X','Clinical Nurse Specialist [Chronic Care]','NUCC Provider Codes'),
   ('364SS0200X','Clinical Nurse Specialist [School]','NUCC Provider Codes'),
   ('364SP0807X','Clinical Nurse Specialist [Psychiatric/Mental Health, Child & Adolescent]','NUCC Provider Codes'),
   ('364SF0001X','Clinical Nurse Specialist [Family Health]','NUCC Provider Codes'),
   ('364SP1700X','Clinical Nurse Specialist [Perinatal]','NUCC Provider Codes'),
   ('364SP0809X','Clinical Nurse Specialist [Psychiatric/Mental Health, Adult]','NUCC Provider Codes'),
   ('364SI0800X','Clinical Nurse Specialist [Informatics]','NUCC Provider Codes'),
   ('364SX0106X','Clinical Nurse Specialist [Occupational Health]','NUCC Provider Codes'),
   ('364SC0200X','Clinical Nurse Specialist [Critical Care Medicine]','NUCC Provider Codes'),
   ('364SA2200X','Clinical Nurse Specialist [Adult Health]','NUCC Provider Codes'),
   ('364SA2100X','Clinical Nurse Specialist [Acute Care]','NUCC Provider Codes'),
   ('208U00000X','Clinical Pharmacology','NUCC Provider Codes'),
   ('208C00000X','Colon & Rectal Surgery','NUCC Provider Codes'),
   ('320800000X','Community Based Residential Treatment Facility, Mental Illness','NUCC Provider Codes'),
   ('320900000X','Community Based Residential Treatment Facility, Mental Retardation and/or  Developmental Disabilities','NUCC Provider Codes'),
   ('172V00000X','Community Health Worker','NUCC Provider Codes'),
   ('251S00000X','Community/Behavioral Health','NUCC Provider Codes'),
   ('171WV0202X','Contractor [Vehicle Modifications]','NUCC Provider Codes'),
   ('171W00000X','Contractor','NUCC Provider Codes'),
   ('171WH0202X','Contractor [Home Modifications]','NUCC Provider Codes'),
   ('101YP2500X','Counselor [Professional]','NUCC Provider Codes'),
   ('101Y00000X','Counselor','NUCC Provider Codes'),
   ('101YA0400X','Counselor [Addiction (Substance Use Disorder)]','NUCC Provider Codes'),
   ('101YM0800X','Counselor [Mental Health]','NUCC Provider Codes'),
   ('101YP1600X','Counselor [Pastoral]','NUCC Provider Codes'),
   ('101YS0200X','Counselor [School]','NUCC Provider Codes'),
   ('311ZA0620X','Custodial Care Facility [Adult Care Home]','NUCC Provider Codes'),
   ('311Z00000X','Custodial Care Facility','NUCC Provider Codes'),
   ('225600000X','Dance Therapist','NUCC Provider Codes'),
   ('251C00000X','Day Training, Developmentally Disabled Services','NUCC Provider Codes'),
   ('373H00000X','Day Training/Habilitation Specialist','NUCC Provider Codes'),
   ('126800000X','Dental Assistant','NUCC Provider Codes'),
   ('124Q00000X','Dental Hygienist','NUCC Provider Codes'),
   ('292200000X','Dental Laboratory','NUCC Provider Codes'),
   ('126900000X','Dental Laboratory Technician','NUCC Provider Codes'),
   ('125J00000X','Dental Therapist','NUCC Provider Codes'),
   ('1223D0001X','Dentist [Dental Public Health]','NUCC Provider Codes'),
   ('1223G0001X','Dentist [General Practice]','NUCC Provider Codes'),
   ('1223S0112X','Dentist [Oral and Maxillofacial Surgery]','NUCC Provider Codes'),
   ('1223P0300X','Dentist [Periodontics]','NUCC Provider Codes'),
   ('1223P0221X','Dentist [Pediatric Dentistry]','NUCC Provider Codes'),
   ('1223P0700X','Dentist [Prosthodontics]','NUCC Provider Codes'),
   ('122300000X','Dentist','NUCC Provider Codes'),
   ('1223X0400X','Dentist [Orthodontics and Dentofacial Orthopedics]','NUCC Provider Codes'),
   ('1223P0106X','Dentist [Oral and Maxillofacial Pathology]','NUCC Provider Codes'),
   ('1223D0004X','Dentist [Dentist Anesthesiologist]','NUCC Provider Codes'),
   ('1223X2210X','Dentist [Orofacial Pain]','NUCC Provider Codes'),
   ('1223E0200X','Dentist [Endodontics]','NUCC Provider Codes'),
   ('1223X0008X','Dentist [Oral and Maxillofacial Radiology]','NUCC Provider Codes'),
   ('122400000X','Denturist','NUCC Provider Codes'),
   ('332100000X','Department of Veterans Affairs (VA) Pharmacy','NUCC Provider Codes'),
   ('207ND0101X','Dermatology [MOHS-Micrographic Surgery]','NUCC Provider Codes'),
   ('207NP0225X','Dermatology [Pediatric Dermatology]','NUCC Provider Codes'),
   ('207NI0002X','Dermatology [Clinical & Laboratory Dermatological Immunology]','NUCC Provider Codes'),
   ('207ND0900X','Dermatology [Dermatopathology]','NUCC Provider Codes'),
   ('207NS0135X','Dermatology [Procedural Dermatology]','NUCC Provider Codes'),
   ('207N00000X','Dermatology','NUCC Provider Codes'),
   ('222Q00000X','Developmental Therapist','NUCC Provider Codes'),
   ('132700000X','Dietary Manager','NUCC Provider Codes'),
   ('136A00000X','Dietetic Technician, Registered','NUCC Provider Codes'),
   ('133VN1006X','Dietitian, Registered [Nutrition, Metabolic]','NUCC Provider Codes'),
   ('133VN1501X','Dietitian, Registered [Nutrition, Sports Dietetics]','NUCC Provider Codes'),
   ('133VN1301X','Dietitian, Registered [Nutrition, Oncology]','NUCC Provider Codes'),
   ('133VN1201X','Dietitian, Registered [Nutrition, Obesity and Weight Management]','NUCC Provider Codes'),
   ('133VN1005X','Dietitian, Registered [Nutrition, Renal]','NUCC Provider Codes'),
   ('133VN1401X','Dietitian, Registered [Nutrition, Pediatric Critical Care]','NUCC Provider Codes'),
   ('133VN1004X','Dietitian, Registered [Nutrition, Pediatric]','NUCC Provider Codes'),
   ('133V00000X','Dietitian, Registered','NUCC Provider Codes'),
   ('133VN1101X','Dietitian, Registered [Nutrition, Gerontological]','NUCC Provider Codes'),
   ('374J00000X','Doula','NUCC Provider Codes'),
   ('172A00000X','Driver','NUCC Provider Codes'),
   ('332BD1200X','Durable Medical Equipment & Medical Supplies [Dialysis Equipment & Supplies]','NUCC Provider Codes'),
   ('332BN1400X','Durable Medical Equipment & Medical Supplies [Nursing Facility Supplies]','NUCC Provider Codes'),
   ('332B00000X','Durable Medical Equipment & Medical Supplies','NUCC Provider Codes'),
   ('332BP3500X','Durable Medical Equipment & Medical Supplies [Parenteral & Enteral Nutrition]','NUCC Provider Codes'),
   ('332BC3200X','Durable Medical Equipment & Medical Supplies [Customized Equipment]','NUCC Provider Codes'),
   ('332BX2000X','Durable Medical Equipment & Medical Supplies [Oxygen Equipment & Supplies]','NUCC Provider Codes'),
   ('252Y00000X','Early Intervention Provider Agency','NUCC Provider Codes'),
   ('204R00000X','Electrodiagnostic Medicine','NUCC Provider Codes'),
   ('146N00000X','Emergency Medical Technician, Basic','NUCC Provider Codes'),
   ('146M00000X','Emergency Medical Technician, Intermediate','NUCC Provider Codes'),
   ('146L00000X','Emergency Medical Technician, Paramedic','NUCC Provider Codes'),
   ('207P00000X','Emergency Medicine','NUCC Provider Codes'),
   ('207PE0005X','Emergency Medicine [Undersea and Hyperbaric Medicine]','NUCC Provider Codes'),
   ('207PT0002X','Emergency Medicine [Medical Toxicology]','NUCC Provider Codes'),
   ('207PH0002X','Emergency Medicine [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('207PE0004X','Emergency Medicine [Emergency Medical Services]','NUCC Provider Codes'),
   ('207PS0010X','Emergency Medicine [Sports Medicine]','NUCC Provider Codes'),
   ('207PP0204X','Emergency Medicine [Pediatric Emergency Medicine]','NUCC Provider Codes'),
   ('333300000X','Emergency Response System Companies','NUCC Provider Codes'),
   ('273100000X','Epilepsy Unit','NUCC Provider Codes'),
   ('302F00000X','Exclusive Provider Organization','NUCC Provider Codes'),
   ('332G00000X','Eye Bank','NUCC Provider Codes'),
   ('332H00000X','Eyewear Supplier','NUCC Provider Codes'),
   ('207QA0401X','Family Medicine [Addiction Medicine]','NUCC Provider Codes'),
   ('207QA0505X','Family Medicine [Adult Medicine]','NUCC Provider Codes'),
   ('207Q00000X','Family Medicine','NUCC Provider Codes'),
   ('207QG0300X','Family Medicine [Geriatric Medicine]','NUCC Provider Codes'),
   ('207QB0002X','Family Medicine [Obesity Medicine]','NUCC Provider Codes'),
   ('207QS1201X','Family Medicine [Sleep Medicine]','NUCC Provider Codes'),
   ('207QH0002X','Family Medicine [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('207QA0000X','Family Medicine [Adolescent Medicine]','NUCC Provider Codes'),
   ('207QS0010X','Family Medicine [Sports Medicine]','NUCC Provider Codes'),
   ('253J00000X','Foster Care Agency','NUCC Provider Codes'),
   ('176P00000X','Funeral Director','NUCC Provider Codes'),
   ('282N00000X','General Acute Care Hospital','NUCC Provider Codes'),
   ('282NC0060X','General Acute Care Hospital [Critical Access]','NUCC Provider Codes'),
   ('282NC2000X','General Acute Care Hospital [Children]','NUCC Provider Codes'),
   ('282NW0100X','General Acute Care Hospital [Women]','NUCC Provider Codes'),
   ('282NR1301X','General Acute Care Hospital [Rural]','NUCC Provider Codes'),
   ('208D00000X','General Practice','NUCC Provider Codes'),
   ('170300000X','Genetic Counselor, MS','NUCC Provider Codes'),
   ('174H00000X','Health Educator','NUCC Provider Codes'),
   ('302R00000X','Health Maintenance Organization','NUCC Provider Codes'),
   ('332S00000X','Hearing Aid Equipment','NUCC Provider Codes'),
   ('237700000X','Hearing Instrument Specialist','NUCC Provider Codes'),
   ('332U00000X','Home Delivered Meals','NUCC Provider Codes'),
   ('251E00000X','Home Health','NUCC Provider Codes'),
   ('374U00000X','Home Health Aide','NUCC Provider Codes'),
   ('251F00000X','Home Infusion','NUCC Provider Codes'),
   ('376J00000X','Homemaker','NUCC Provider Codes'),
   ('175L00000X','Homeopath','NUCC Provider Codes'),
   ('251G00000X','Hospice Care, Community Based','NUCC Provider Codes'),
   ('315D00000X','Hospice, Inpatient','NUCC Provider Codes'),
   ('208M00000X','Hospitalist','NUCC Provider Codes'),
   ('253Z00000X','In Home Supportive Care','NUCC Provider Codes'),
   ('202C00000X','Independent Medical Examiner','NUCC Provider Codes'),
   ('332800000X','Indian Health Service/Tribal/Urban Indian Health (I/T/U) Pharmacy','NUCC Provider Codes'),
   ('310500000X','Intermediate Care Facility, Mental Illness','NUCC Provider Codes'),
   ('315P00000X','Intermediate Care Facility, Mentally Retarded','NUCC Provider Codes'),
   ('207RM1200X','Internal Medicine [Magnetic Resonance Imaging (MRI)]','NUCC Provider Codes'),
   ('207RT0003X','Internal Medicine [Transplant Hepatology]','NUCC Provider Codes'),
   ('207RI0200X','Internal Medicine [Infectious Disease]','NUCC Provider Codes'),
   ('207RC0001X','Internal Medicine [Clinical Cardiac Electrophysiology]','NUCC Provider Codes'),
   ('207RC0000X','Internal Medicine [Cardiovascular Disease]','NUCC Provider Codes'),
   ('207RS0010X','Internal Medicine [Sports Medicine]','NUCC Provider Codes'),
   ('207RH0005X','Internal Medicine [Hypertension Specialist]','NUCC Provider Codes'),
   ('207RH0002X','Internal Medicine [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('207RA0401X','Internal Medicine [Addiction Medicine]','NUCC Provider Codes'),
   ('207RI0001X','Internal Medicine [Clinical & Laboratory Immunology]','NUCC Provider Codes'),
   ('207RA0002X','Internal Medicine [Adult Congenital Heart Disease]','NUCC Provider Codes'),
   ('207RH0003X','Internal Medicine [Hematology & Oncology]','NUCC Provider Codes'),
   ('207RI0011X','Internal Medicine [Interventional Cardiology]','NUCC Provider Codes'),
   ('207RA0000X','Internal Medicine [Adolescent Medicine]','NUCC Provider Codes'),
   ('207RB0002X','Internal Medicine [Obesity Medicine]','NUCC Provider Codes'),
   ('207RA0201X','Internal Medicine [Allergy & Immunology]','NUCC Provider Codes'),
   ('207RN0300X','Internal Medicine [Nephrology]','NUCC Provider Codes'),
   ('207RR0500X','Internal Medicine [Rheumatology]','NUCC Provider Codes'),
   ('207RE0101X','Internal Medicine [Endocrinology, Diabetes & Metabolism]','NUCC Provider Codes'),
   ('207RS0012X','Internal Medicine [Sleep Medicine]','NUCC Provider Codes'),
   ('207RC0200X','Internal Medicine [Critical Care Medicine]','NUCC Provider Codes'),
   ('207RP1001X','Internal Medicine [Pulmonary Disease]','NUCC Provider Codes'),
   ('207RG0100X','Internal Medicine [Gastroenterology]','NUCC Provider Codes'),
   ('207RH0000X','Internal Medicine [Hematology]','NUCC Provider Codes'),
   ('207R00000X','Internal Medicine','NUCC Provider Codes'),
   ('207RI0008X','Internal Medicine [Hepatology]','NUCC Provider Codes'),
   ('207RG0300X','Internal Medicine [Geriatric Medicine]','NUCC Provider Codes'),
   ('207RA0001X','Internal Medicine [Advanced Heart Failure and Transplant Cardiology]','NUCC Provider Codes'),
   ('207RX0202X','Internal Medicine [Medical Oncology]','NUCC Provider Codes'),
   ('171R00000X','Interpreter','NUCC Provider Codes'),
   ('226300000X','Kinesiotherapist','NUCC Provider Codes'),
   ('174N00000X','Lactation Consultant, Non-RN','NUCC Provider Codes'),
   ('209800000X','Legal Medicine','NUCC Provider Codes'),
   ('173000000X','Legal Medicine','NUCC Provider Codes'),
   ('164W00000X','Licensed Practical Nurse','NUCC Provider Codes'),
   ('167G00000X','Licensed Psychiatric Technician','NUCC Provider Codes'),
   ('164X00000X','Licensed Vocational Nurse','NUCC Provider Codes'),
   ('251300000X','Local Education Agency (LEA)','NUCC Provider Codes'),
   ('177F00000X','Lodging','NUCC Provider Codes'),
   ('282E00000X','Long Term Care Hospital','NUCC Provider Codes'),
   ('106H00000X','Marriage & Family Therapist','NUCC Provider Codes'),
   ('225700000X','Massage Therapist','NUCC Provider Codes'),
   ('224900000X','Mastectomy Fitter','NUCC Provider Codes'),
   ('174200000X','Meals','NUCC Provider Codes'),
   ('172M00000X','Mechanotherapist','NUCC Provider Codes'),
   ('335G00000X','Medical Foods Supplier','NUCC Provider Codes'),
   ('207SG0202X','Medical Genetics [Clinical Biochemical Genetics]','NUCC Provider Codes'),
   ('207SG0201X','Medical Genetics [Clinical Genetics (M.D.)]','NUCC Provider Codes'),
   ('207SG0205X','Medical Genetics [Ph.D. Medical Genetics]','NUCC Provider Codes'),
   ('207SG0203X','Medical Genetics [Clinical Molecular Genetics]','NUCC Provider Codes'),
   ('207SC0300X','Medical Genetics [Clinical Cytogenetics]','NUCC Provider Codes'),
   ('207SM0001X','Medical Genetics [Molecular Genetic Pathology]','NUCC Provider Codes'),
   ('170100000X','Medical Genetics, Ph.D. Medical Genetics','NUCC Provider Codes'),
   ('275N00000X','Medicare Defined Swing Bed Unit','NUCC Provider Codes'),
   ('176B00000X','Midwife','NUCC Provider Codes'),
   ('175M00000X','Midwife, Lay','NUCC Provider Codes'),
   ('291900000X','Military Clinical Medical Laboratory','NUCC Provider Codes'),
   ('1710I1002X','Military Health Care Provider [Independent Duty Corpsman]','NUCC Provider Codes'),
   ('171000000X','Military Health Care Provider','NUCC Provider Codes'),
   ('1710I1003X','Military Health Care Provider [Independent Duty Medical Technicians]','NUCC Provider Codes'),
   ('2865M2000X','Military Hospital [Military General Acute Care Hospital]','NUCC Provider Codes'),
   ('2865C1500X','Military Hospital [Community Health]','NUCC Provider Codes'),
   ('2865X1600X','Military Hospital [Military General Acute Care Hospital. Operational (Transportable)]','NUCC Provider Codes'),
   ('286500000X','Military Hospital','NUCC Provider Codes'),
   ('332000000X','Military/U.S. Coast Guard Pharmacy','NUCC Provider Codes'),
   ('3418M1120X','Military/U.S. Coast Guard Transport [Military or U.S. Coast Guard Ambulance,  Air Transport]','NUCC Provider Codes'),
   ('3418M1130X','Military/U.S. Coast Guard Transport [Military or U.S. Coast Guard Ambulance,  Water Transport]','NUCC Provider Codes'),
   ('341800000X','Military/U.S. Coast Guard Transport','NUCC Provider Codes'),
   ('3418M1110X','Military/U.S. Coast Guard Transport [Military or U.S. Coast Guard Ambulance,  Ground Transport]','NUCC Provider Codes'),
   ('193200000X','Multi-Specialty','NUCC Provider Codes'),
   ('225A00000X','Music Therapist','NUCC Provider Codes'),
   ('172P00000X','Naprapath','NUCC Provider Codes'),
   ('175F00000X','Naturopath','NUCC Provider Codes'),
   ('207T00000X','Neurological Surgery','NUCC Provider Codes'),
   ('204D00000X','Neuromusculoskeletal Medicine & OMM','NUCC Provider Codes'),
   ('204C00000X','Neuromusculoskeletal Medicine, Sports Medicine','NUCC Provider Codes'),
   ('343900000X','Non-emergency Medical Transport (VAN)','NUCC Provider Codes'),
   ('332900000X','Non-Pharmacy Dispensing Site','NUCC Provider Codes'),
   ('207UN0902X','Nuclear Medicine [Nuclear Imaging & Therapy]','NUCC Provider Codes'),
   ('207U00000X','Nuclear Medicine','NUCC Provider Codes'),
   ('207UN0903X','Nuclear Medicine [In Vivo & In Vitro Nuclear Medicine]','NUCC Provider Codes'),
   ('207UN0901X','Nuclear Medicine [Nuclear Cardiology]','NUCC Provider Codes'),
   ('367500000X','Nurse Anesthetist, Certified Registered','NUCC Provider Codes'),
   ('363LX0106X','Nurse Practitioner [Occupational Health]','NUCC Provider Codes'),
   ('363LS0200X','Nurse Practitioner [School]','NUCC Provider Codes'),
   ('363LP0200X','Nurse Practitioner [Pediatrics]','NUCC Provider Codes'),
   ('363L00000X','Nurse Practitioner','NUCC Provider Codes'),
   ('363LC0200X','Nurse Practitioner [Critical Care Medicine]','NUCC Provider Codes'),
   ('363LP1700X','Nurse Practitioner [Perinatal]','NUCC Provider Codes'),
   ('363LN0000X','Nurse Practitioner [Neonatal]','NUCC Provider Codes'),
   ('363LP0222X','Nurse Practitioner [Pediatrics, Critical Care]','NUCC Provider Codes'),
   ('363LG0600X','Nurse Practitioner [Gerontology]','NUCC Provider Codes'),
   ('363LP0808X','Nurse Practitioner [Psychiatric/Mental Health]','NUCC Provider Codes'),
   ('363LA2100X','Nurse Practitioner [Acute Care]','NUCC Provider Codes'),
   ('363LN0005X','Nurse Practitioner [Neonatal, Critical Care]','NUCC Provider Codes'),
   ('363LF0000X','Nurse Practitioner [Family]','NUCC Provider Codes'),
   ('363LC1500X','Nurse Practitioner [Community Health]','NUCC Provider Codes'),
   ('363LP2300X','Nurse Practitioner [Primary Care]','NUCC Provider Codes'),
   ('363LW0102X','Nurse Practitioner [Women''s Health]','NUCC Provider Codes'),
   ('363LX0001X','Nurse Practitioner [Obstetrics & Gynecology]','NUCC Provider Codes'),
   ('363LA2200X','Nurse Practitioner [Adult Health]','NUCC Provider Codes'),
   ('376K00000X','Nurse''s Aide','NUCC Provider Codes'),
   ('251J00000X','Nursing Care','NUCC Provider Codes'),
   ('313M00000X','Nursing Facility/Intermediate Care Facility','NUCC Provider Codes'),
   ('376G00000X','Nursing Home Administrator','NUCC Provider Codes'),
   ('133NN1002X','Nutritionist [Nutrition, Education]','NUCC Provider Codes'),
   ('133N00000X','Nutritionist','NUCC Provider Codes'),
   ('207V00000X','Obstetrics & Gynecology','NUCC Provider Codes'),
   ('207VM0101X','Obstetrics & Gynecology [Maternal & Fetal Medicine]','NUCC Provider Codes'),
   ('207VH0002X','Obstetrics & Gynecology [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('207VE0102X','Obstetrics & Gynecology [Reproductive Endocrinology]','NUCC Provider Codes'),
   ('207VG0400X','Obstetrics & Gynecology [Gynecology]','NUCC Provider Codes'),
   ('207VF0040X','Obstetrics & Gynecology [Female Pelvic Medicine and Reconstructive Surgery]','NUCC Provider Codes'),
   ('207VC0200X','Obstetrics & Gynecology [Critical Care Medicine]','NUCC Provider Codes'),
   ('207VX0201X','Obstetrics & Gynecology [Gynecologic Oncology]','NUCC Provider Codes'),
   ('207VX0000X','Obstetrics & Gynecology [Obstetrics]','NUCC Provider Codes'),
   ('207VB0002X','Obstetrics & Gynecology [Obesity Medicine]','NUCC Provider Codes'),
   ('225XL0004X','Occupational Therapist [Low Vision]','NUCC Provider Codes'),
   ('225XP0200X','Occupational Therapist [Pediatrics]','NUCC Provider Codes'),
   ('225XH1200X','Occupational Therapist [Hand]','NUCC Provider Codes'),
   ('225XE0001X','Occupational Therapist [Environmental Modification]','NUCC Provider Codes'),
   ('225XF0002X','Occupational Therapist [Feeding, Eating & Swallowing]','NUCC Provider Codes'),
   ('225XP0019X','Occupational Therapist [Physical Rehabilitation]','NUCC Provider Codes'),
   ('225XM0800X','Occupational Therapist [Mental Health]','NUCC Provider Codes'),
   ('225XR0403X','Occupational Therapist [Driving and Community Mobility]','NUCC Provider Codes'),
   ('225XH1300X','Occupational Therapist [Human Factors]','NUCC Provider Codes'),
   ('225XE1200X','Occupational Therapist [Ergonomics]','NUCC Provider Codes'),
   ('225XG0600X','Occupational Therapist [Gerontology]','NUCC Provider Codes'),
   ('225XN1300X','Occupational Therapist [Neurorehabilitation]','NUCC Provider Codes'),
   ('225X00000X','Occupational Therapist','NUCC Provider Codes'),
   ('224ZL0004X','Occupational Therapy Assistant [Low Vision]','NUCC Provider Codes'),
   ('224Z00000X','Occupational Therapy Assistant','NUCC Provider Codes'),
   ('224ZE0001X','Occupational Therapy Assistant [Environmental Modification]','NUCC Provider Codes'),
   ('224ZR0403X','Occupational Therapy Assistant [Driving and Community Mobility]','NUCC Provider Codes'),
   ('224ZF0002X','Occupational Therapy Assistant [Feeding, Eating & Swallowing]','NUCC Provider Codes'),
   ('207WX0109X','Ophthalmology [Neuro-ophthalmology]','NUCC Provider Codes'),
   ('207WX0200X','Ophthalmology [Ophthalmic Plastic and Reconstructive Surgery]','NUCC Provider Codes'),
   ('207WX0120X','Ophthalmology [Cornea and External Diseases Specialist]','NUCC Provider Codes'),
   ('207WX0108X','Ophthalmology [Uveitis and Ocular Inflammatory Disease]','NUCC Provider Codes'),
   ('207WX0107X','Ophthalmology [Retina Specialist]','NUCC Provider Codes'),
   ('207W00000X','Ophthalmology','NUCC Provider Codes'),
   ('207WX0009X','Ophthalmology [Glaucoma Specialist]','NUCC Provider Codes'),
   ('207WX0110X','Ophthalmology [Pediatric Ophthalmology and Strabismus Specialist]','NUCC Provider Codes'),
   ('152WL0500X','Optometrist [Low Vision Rehabilitation]','NUCC Provider Codes'),
   ('152WV0400X','Optometrist [Vision Therapy]','NUCC Provider Codes'),
   ('152WS0006X','Optometrist [Sports Vision]','NUCC Provider Codes'),
   ('152WX0102X','Optometrist [Occupational Vision]','NUCC Provider Codes'),
   ('152W00000X','Optometrist','NUCC Provider Codes'),
   ('152WP0200X','Optometrist [Pediatrics]','NUCC Provider Codes'),
   ('152WC0802X','Optometrist [Corneal and Contact Management]','NUCC Provider Codes'),
   ('204E00000X','Oral & Maxillofacial Surgery','NUCC Provider Codes'),
   ('125Q00000X','Oral Medicinist','NUCC Provider Codes'),
   ('335U00000X','Organ Procurement Organization','NUCC Provider Codes'),
   ('207XX0801X','Orthopaedic Surgery [Orthopaedic Trauma]','NUCC Provider Codes'),
   ('207XS0117X','Orthopaedic Surgery [Orthopaedic Surgery of the Spine]','NUCC Provider Codes'),
   ('207XX0004X','Orthopaedic Surgery [Foot and Ankle Surgery]','NUCC Provider Codes'),
   ('207XS0114X','Orthopaedic Surgery [Adult Reconstructive Orthopaedic Surgery]','NUCC Provider Codes'),
   ('207X00000X','Orthopaedic Surgery','NUCC Provider Codes'),
   ('207XX0005X','Orthopaedic Surgery [Sports Medicine]','NUCC Provider Codes'),
   ('207XP3100X','Orthopaedic Surgery [Pediatric Orthopaedic Surgery]','NUCC Provider Codes'),
   ('207XS0106X','Orthopaedic Surgery [Hand Surgery]','NUCC Provider Codes'),
   ('225000000X','Orthotic Fitter','NUCC Provider Codes'),
   ('222Z00000X','Orthotist','NUCC Provider Codes'),
   ('207YP0228X','Otolaryngology [Pediatric Otolaryngology]','NUCC Provider Codes'),
   ('207Y00000X','Otolaryngology','NUCC Provider Codes'),
   ('207YX0905X','Otolaryngology [Otolaryngology/Facial Plastic Surgery]','NUCC Provider Codes'),
   ('207YS0123X','Otolaryngology [Facial Plastic Surgery]','NUCC Provider Codes'),
   ('207YX0602X','Otolaryngology [Otolaryngic Allergy]','NUCC Provider Codes'),
   ('207YS0012X','Otolaryngology [Sleep Medicine]','NUCC Provider Codes'),
   ('207YX0007X','Otolaryngology [Plastic Surgery within the Head & Neck]','NUCC Provider Codes'),
   ('207YX0901X','Otolaryngology [Otology & Neurotology]','NUCC Provider Codes'),
   ('208VP0014X','Pain Medicine [Interventional Pain Medicine]','NUCC Provider Codes'),
   ('208VP0000X','Pain Medicine [Pain Medicine]','NUCC Provider Codes'),
   ('207ZP0105X','Pathology [Clinical Pathology/Laboratory Medicine]','NUCC Provider Codes'),
   ('207ZP0101X','Pathology [Anatomic Pathology]','NUCC Provider Codes'),
   ('207ZC0008X','Pathology [Clinical Informatics]','NUCC Provider Codes'),
   ('207ZP0104X','Pathology [Chemical Pathology]','NUCC Provider Codes'),
   ('207ZI0100X','Pathology [Immunopathology]','NUCC Provider Codes'),
   ('207ZC0006X','Pathology [Clinical Pathology]','NUCC Provider Codes'),
   ('207ZN0500X','Pathology [Neuropathology]','NUCC Provider Codes'),
   ('207ZP0213X','Pathology [Pediatric Pathology]','NUCC Provider Codes'),
   ('207ZC0500X','Pathology [Cytopathology]','NUCC Provider Codes'),
   ('207ZD0900X','Pathology [Dermatopathology]','NUCC Provider Codes'),
   ('207ZP0102X','Pathology [Anatomic Pathology & Clinical Pathology]','NUCC Provider Codes'),
   ('207ZH0000X','Pathology [Hematology]','NUCC Provider Codes'),
   ('207ZB0001X','Pathology [Blood Banking & Transfusion Medicine]','NUCC Provider Codes'),
   ('207ZM0300X','Pathology [Medical Microbiology]','NUCC Provider Codes'),
   ('207ZP0007X','Pathology [Molecular Genetic Pathology]','NUCC Provider Codes'),
   ('207ZF0201X','Pathology [Forensic Pathology]','NUCC Provider Codes'),
   ('247ZC0005X','Pathology [Clinical Laboratory Director, Non-physician]','NUCC Provider Codes'),
   ('2080P0207X','Pediatrics [Pediatric Hematology-Oncology]','NUCC Provider Codes'),
   ('2080C0008X','Pediatrics [Child Abuse Pediatrics]','NUCC Provider Codes'),
   ('2080P0204X','Pediatrics [Pediatric Emergency Medicine]','NUCC Provider Codes'),
   ('2080P0210X','Pediatrics [Pediatric Nephrology]','NUCC Provider Codes'),
   ('208000000X','Pediatrics','NUCC Provider Codes'),
   ('2080P0202X','Pediatrics [Pediatric Cardiology]','NUCC Provider Codes'),
   ('2080A0000X','Pediatrics [Adolescent Medicine]','NUCC Provider Codes'),
   ('2080P0203X','Pediatrics [Pediatric Critical Care Medicine]','NUCC Provider Codes'),
   ('2080P0006X','Pediatrics [Developmental - Behavioral Pediatrics]','NUCC Provider Codes'),
   ('2080P0201X','Pediatrics [Pediatric Allergy/Immunology]','NUCC Provider Codes'),
   ('2080P0214X','Pediatrics [Pediatric Pulmonology]','NUCC Provider Codes'),
   ('2080T0002X','Pediatrics [Medical Toxicology]','NUCC Provider Codes'),
   ('2080P0206X','Pediatrics [Pediatric Gastroenterology]','NUCC Provider Codes'),
   ('2080P0008X','Pediatrics [Neurodevelopmental Disabilities]','NUCC Provider Codes'),
   ('2080S0012X','Pediatrics [Sleep Medicine]','NUCC Provider Codes'),
   ('2080T0004X','Pediatrics [Pediatric Transplant Hepatology]','NUCC Provider Codes'),
   ('2080P0208X','Pediatrics [Pediatric Infectious Diseases]','NUCC Provider Codes'),
   ('2080I0007X','Pediatrics [Clinical & Laboratory Immunology]','NUCC Provider Codes'),
   ('2080P0216X','Pediatrics [Pediatric Rheumatology]','NUCC Provider Codes'),
   ('2080H0002X','Pediatrics [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('2080B0002X','Pediatrics [Obesity Medicine]','NUCC Provider Codes'),
   ('2080S0010X','Pediatrics [Sports Medicine]','NUCC Provider Codes'),
   ('2080P0205X','Pediatrics [Pediatric Endocrinology]','NUCC Provider Codes'),
   ('2080N0001X','Pediatrics [Neonatal-Perinatal Medicine]','NUCC Provider Codes'),
   ('224L00000X','Pedorthist','NUCC Provider Codes'),
   ('175T00000X','Peer Specialist','NUCC Provider Codes'),
   ('242T00000X','Perfusionist','NUCC Provider Codes'),
   ('146D00000X','Personal Emergency Response Attendant','NUCC Provider Codes'),
   ('1835P1300X','Pharmacist [Psychiatric]','NUCC Provider Codes'),
   ('1835G0303X','Pharmacist [Geriatric]','NUCC Provider Codes'),
   ('1835P0200X','Pharmacist [Pediatrics]','NUCC Provider Codes'),
   ('1835C0205X','Pharmacist [Critical Care]','NUCC Provider Codes'),
   ('1835N0905X','Pharmacist [Nuclear]','NUCC Provider Codes'),
   ('1835P2201X','Pharmacist [Ambulatory Care]','NUCC Provider Codes'),
   ('1835P1200X','Pharmacist [Pharmacotherapy]','NUCC Provider Codes'),
   ('183500000X','Pharmacist','NUCC Provider Codes'),
   ('1835N1003X','Pharmacist [Nutrition Support]','NUCC Provider Codes'),
   ('1835P0018X','Pharmacist [Pharmacist Clinician (PhC)/ Clinical Pharmacy Specialist]','NUCC Provider Codes'),
   ('1835G0000X','Pharmacist [General Practice]','NUCC Provider Codes'),
   ('1835X0200X','Pharmacist [Oncology]','NUCC Provider Codes'),
   ('3336M0002X','Pharmacy [Mail Order Pharmacy]','NUCC Provider Codes'),
   ('3336C0004X','Pharmacy [Compounding Pharmacy]','NUCC Provider Codes'),
   ('3336C0002X','Pharmacy [Clinic Pharmacy]','NUCC Provider Codes'),
   ('3336N0007X','Pharmacy [Nuclear Pharmacy]','NUCC Provider Codes'),
   ('3336H0001X','Pharmacy [Home Infusion Therapy Pharmacy]','NUCC Provider Codes'),
   ('3336I0012X','Pharmacy [Institutional Pharmacy]','NUCC Provider Codes'),
   ('3336C0003X','Pharmacy [Community/Retail Pharmacy]','NUCC Provider Codes'),
   ('3336S0011X','Pharmacy [Specialty Pharmacy]','NUCC Provider Codes'),
   ('333600000X','Pharmacy','NUCC Provider Codes'),
   ('3336L0003X','Pharmacy [Long Term Care Pharmacy]','NUCC Provider Codes'),
   ('3336M0003X','Pharmacy [Managed Care Organization Pharmacy]','NUCC Provider Codes'),
   ('183700000X','Pharmacy Technician','NUCC Provider Codes'),
   ('202K00000X','Phlebology','NUCC Provider Codes'),
   ('2081P2900X','Physical Medicine & Rehabilitation [Pain Medicine]','NUCC Provider Codes'),
   ('2081P0004X','Physical Medicine & Rehabilitation [Spinal Cord Injury Medicine]','NUCC Provider Codes'),
   ('2081P0010X','Physical Medicine & Rehabilitation [Pediatric Rehabilitation Medicine]','NUCC Provider Codes'),
   ('2081S0010X','Physical Medicine & Rehabilitation [Sports Medicine]','NUCC Provider Codes'),
   ('2081P0301X','Physical Medicine & Rehabilitation [Brain Injury Medicine]','NUCC Provider Codes'),
   ('2081H0002X','Physical Medicine & Rehabilitation [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('2081N0008X','Physical Medicine & Rehabilitation [Neuromuscular Medicine]','NUCC Provider Codes'),
   ('208100000X','Physical Medicine & Rehabilitation','NUCC Provider Codes'),
   ('2251X0800X','Physical Therapist [Orthopedic]','NUCC Provider Codes'),
   ('2251G0304X','Physical Therapist [Geriatrics]','NUCC Provider Codes'),
   ('2251E1200X','Physical Therapist [Ergonomics]','NUCC Provider Codes'),
   ('225100000X','Physical Therapist','NUCC Provider Codes'),
   ('2251N0400X','Physical Therapist [Neurology]','NUCC Provider Codes'),
   ('2251H1300X','Physical Therapist [Human Factors]','NUCC Provider Codes'),
   ('2251S0007X','Physical Therapist [Sports]','NUCC Provider Codes'),
   ('2251E1300X','Physical Therapist [Electrophysiology, Clinical]','NUCC Provider Codes'),
   ('2251P0200X','Physical Therapist [Pediatrics]','NUCC Provider Codes'),
   ('2251H1200X','Physical Therapist [Hand]','NUCC Provider Codes'),
   ('2251C2600X','Physical Therapist [Cardiopulmonary]','NUCC Provider Codes'),
   ('225200000X','Physical Therapy Assistant','NUCC Provider Codes'),
   ('363AS0400X','Physician Assistant [Surgical]','NUCC Provider Codes'),
   ('363A00000X','Physician Assistant','NUCC Provider Codes'),
   ('363AM0700X','Physician Assistant [Medical]','NUCC Provider Codes'),
   ('293D00000X','Physiological Laboratory','NUCC Provider Codes'),
   ('2082S0105X','Plastic Surgery [Surgery of the Hand]','NUCC Provider Codes'),
   ('208200000X','Plastic Surgery','NUCC Provider Codes'),
   ('2082S0099X','Plastic Surgery [Plastic Surgery Within the Head and Neck]','NUCC Provider Codes'),
   ('213EP1101X','Podiatrist [Primary Podiatric Medicine]','NUCC Provider Codes'),
   ('213ES0103X','Podiatrist [Foot & Ankle Surgery]','NUCC Provider Codes'),
   ('213ES0000X','Podiatrist [Sports Medicine]','NUCC Provider Codes'),
   ('213E00000X','Podiatrist','NUCC Provider Codes'),
   ('213EP0504X','Podiatrist [Public Medicine]','NUCC Provider Codes'),
   ('213ER0200X','Podiatrist [Radiology]','NUCC Provider Codes'),
   ('213EG0000X','Podiatrist [General Practice]','NUCC Provider Codes'),
   ('213ES0131X','Podiatrist [Foot Surgery]','NUCC Provider Codes'),
   ('102X00000X','Poetry Therapist','NUCC Provider Codes'),
   ('305S00000X','Point of Service','NUCC Provider Codes'),
   ('335V00000X','Portable X-ray and/or Other Portable Diagnostic Imaging Supplier','NUCC Provider Codes'),
   ('305R00000X','Preferred Provider Organization','NUCC Provider Codes'),
   ('405300000X','Prevention Professional','NUCC Provider Codes'),
   ('2083A0300X','Preventive Medicine [Addiction Medicine]','NUCC Provider Codes'),
   ('2083T0002X','Preventive Medicine [Medical Toxicology]','NUCC Provider Codes'),
   ('2083A0100X','Preventive Medicine [Aerospace Medicine]','NUCC Provider Codes'),
   ('2083B0002X','Preventive Medicine [Obesity Medicine]','NUCC Provider Codes'),
   ('2083P0011X','Preventive Medicine [Undersea and Hyperbaric Medicine]','NUCC Provider Codes'),
   ('2083S0010X','Preventive Medicine [Sports Medicine]','NUCC Provider Codes'),
   ('2083C0008X','Preventive Medicine [Clinical Informatics]','NUCC Provider Codes'),
   ('2083X0100X','Preventive Medicine [Occupational Medicine]','NUCC Provider Codes'),
   ('2083P0901X','Preventive Medicine [Public Health & General Preventive Medicine]','NUCC Provider Codes'),
   ('2083P0500X','Preventive Medicine [Preventive Medicine/Occupational Environmental Medicine]','NUCC Provider Codes'),
   ('347C00000X','Private Vehicle','NUCC Provider Codes'),
   ('251T00000X','Program of All-Inclusive Care for the Elderly (PACE) Provider Organization','NUCC Provider Codes'),
   ('335E00000X','Prosthetic/Orthotic Supplier','NUCC Provider Codes'),
   ('224P00000X','Prosthetist','NUCC Provider Codes'),
   ('283Q00000X','Psychiatric Hospital','NUCC Provider Codes'),
   ('323P00000X','Psychiatric Residential Treatment Facility','NUCC Provider Codes'),
   ('273R00000X','Psychiatric Unit','NUCC Provider Codes'),
   ('2084S0010X','Psychiatry & Neurology [Sports Medicine]','NUCC Provider Codes'),
   ('2084H0002X','Psychiatry & Neurology [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('2084P0301X','Psychiatry & Neurology [Brain Injury Medicine]','NUCC Provider Codes'),
   ('2084P0800X','Psychiatry & Neurology [Psychiatry]','NUCC Provider Codes'),
   ('2084N0400X','Psychiatry & Neurology [Neurology]','NUCC Provider Codes'),
   ('2084A0401X','Psychiatry & Neurology [Addiction Medicine]','NUCC Provider Codes'),
   ('2084P0805X','Psychiatry & Neurology [Geriatric Psychiatry]','NUCC Provider Codes'),
   ('2084P0804X','Psychiatry & Neurology [Child & Adolescent Psychiatry]','NUCC Provider Codes'),
   ('2084P0005X','Psychiatry & Neurology [Neurodevelopmental Disabilities]','NUCC Provider Codes'),
   ('2084V0102X','Psychiatry & Neurology [Vascular Neurology]','NUCC Provider Codes'),
   ('2084B0040X','Psychiatry & Neurology [Behavioral Neurology & Neuropsychiatry]','NUCC Provider Codes'),
   ('2084N0008X','Psychiatry & Neurology [Neuromuscular Medicine]','NUCC Provider Codes'),
   ('2084A2900X','Psychiatry & Neurology [Neurocritical Care]','NUCC Provider Codes'),
   ('2084P0802X','Psychiatry & Neurology [Addiction Psychiatry]','NUCC Provider Codes'),
   ('2084P0015X','Psychiatry & Neurology [Psychosomatic Medicine]','NUCC Provider Codes'),
   ('2084N0600X','Psychiatry & Neurology [Clinical Neurophysiology]','NUCC Provider Codes'),
   ('2084N0402X','Psychiatry & Neurology [Neurology with Special Qualifications in Child  Neurology]','NUCC Provider Codes'),
   ('2084S0012X','Psychiatry & Neurology [Sleep Medicine]','NUCC Provider Codes'),
   ('2084P2900X','Psychiatry & Neurology [Pain Medicine]','NUCC Provider Codes'),
   ('2084F0202X','Psychiatry & Neurology [Forensic Psychiatry]','NUCC Provider Codes'),
   ('2084B0002X','Psychiatry & Neurology [Obesity Medicine]','NUCC Provider Codes'),
   ('2084D0003X','Psychiatry & Neurology [Diagnostic Neuroimaging]','NUCC Provider Codes'),
   ('102L00000X','Psychoanalyst','NUCC Provider Codes'),
   ('103TH0004X','Psychologist [Health]','NUCC Provider Codes'),
   ('103TW0100X','Psychologist [Women]','NUCC Provider Codes'),
   ('103TP0016X','Psychologist [Prescribing (Medical)]','NUCC Provider Codes'),
   ('103TF0200X','Psychologist [Forensic]','NUCC Provider Codes'),
   ('103T00000X','Psychologist','NUCC Provider Codes'),
   ('103TA0400X','Psychologist [Addiction (Substance Use Disorder)]','NUCC Provider Codes'),
   ('103TM1800X','Psychologist [Mental Retardation & Developmental Disabilities]','NUCC Provider Codes'),
   ('103TS0200X','Psychologist [School]','NUCC Provider Codes'),
   ('103TE1100X','Psychologist [Exercise & Sports]','NUCC Provider Codes'),
   ('103TP2700X','Psychologist [Psychotherapy]','NUCC Provider Codes'),
   ('103TA0700X','Psychologist [Adult Development & Aging]','NUCC Provider Codes'),
   ('103TM1700X','Psychologist [Men & Masculinity]','NUCC Provider Codes'),
   ('103TC2200X','Psychologist [Clinical Child & Adolescent]','NUCC Provider Codes'),
   ('103TB0200X','Psychologist [Cognitive & Behavioral]','NUCC Provider Codes'),
   ('103TC1900X','Psychologist [Counseling]','NUCC Provider Codes'),
   ('103TE1000X','Psychologist [Educational]','NUCC Provider Codes'),
   ('103TF0000X','Psychologist [Family]','NUCC Provider Codes'),
   ('103TR0400X','Psychologist [Rehabilitation]','NUCC Provider Codes'),
   ('103TH0100X','Psychologist [Health Service]','NUCC Provider Codes'),
   ('103TC0700X','Psychologist [Clinical]','NUCC Provider Codes'),
   ('103TP0814X','Psychologist [Psychoanalysis]','NUCC Provider Codes'),
   ('103TP2701X','Psychologist [Group Psychotherapy]','NUCC Provider Codes'),
   ('251K00000X','Public Health or Welfare','NUCC Provider Codes'),
   ('225B00000X','Pulmonary Function Technologist','NUCC Provider Codes'),
   ('2471S1302X','Radiologic Technologist [Sonography]','NUCC Provider Codes'),
   ('2471M2300X','Radiologic Technologist [Mammography]','NUCC Provider Codes'),
   ('2471C3401X','Radiologic Technologist [Computed Tomography]','NUCC Provider Codes'),
   ('2471V0105X','Radiologic Technologist [Vascular Sonography]','NUCC Provider Codes'),
   ('2471N0900X','Radiologic Technologist [Nuclear Medicine Technology]','NUCC Provider Codes'),
   ('2471V0106X','Radiologic Technologist [Vascular-Interventional Technology]','NUCC Provider Codes'),
   ('2471C1101X','Radiologic Technologist [Cardiovascular-Interventional Technology]','NUCC Provider Codes'),
   ('2471B0102X','Radiologic Technologist [Bone Densitometry]','NUCC Provider Codes'),
   ('2471C3402X','Radiologic Technologist [Radiography]','NUCC Provider Codes'),
   ('247100000X','Radiologic Technologist','NUCC Provider Codes'),
   ('2471R0002X','Radiologic Technologist [Radiation Therapy]','NUCC Provider Codes'),
   ('2471M1202X','Radiologic Technologist [Magnetic Resonance Imaging]','NUCC Provider Codes'),
   ('2471Q0001X','Radiologic Technologist [Quality Management]','NUCC Provider Codes'),
   ('2471C1106X','Radiologic Technologist [Cardiac-Interventional Technology]','NUCC Provider Codes'),
   ('2085U0001X','Radiology [Diagnostic Ultrasound]','NUCC Provider Codes'),
   ('2085R0205X','Radiology [Radiological Physics]','NUCC Provider Codes'),
   ('2085N0700X','Radiology [Neuroradiology]','NUCC Provider Codes'),
   ('2085H0002X','Radiology [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('2085R0202X','Radiology [Diagnostic Radiology]','NUCC Provider Codes'),
   ('2085D0003X','Radiology [Diagnostic Neuroimaging]','NUCC Provider Codes'),
   ('2085B0100X','Radiology [Body Imaging]','NUCC Provider Codes'),
   ('2085R0204X','Radiology [Vascular & Interventional Radiology]','NUCC Provider Codes'),
   ('2085R0203X','Radiology [Therapeutic Radiology]','NUCC Provider Codes'),
   ('2085P0229X','Radiology [Pediatric Radiology]','NUCC Provider Codes'),
   ('2085R0001X','Radiology [Radiation Oncology]','NUCC Provider Codes'),
   ('2085N0904X','Radiology [Nuclear Radiology]','NUCC Provider Codes'),
   ('243U00000X','Radiology Practitioner Assistant','NUCC Provider Codes'),
   ('225800000X','Recreation Therapist','NUCC Provider Codes'),
   ('226000000X','Recreational Therapist Assistant','NUCC Provider Codes'),
   ('173C00000X','Reflexologist','NUCC Provider Codes'),
   ('163WN0003X','Registered Nurse [Neonatal, Low-Risk]','NUCC Provider Codes'),
   ('163WR0400X','Registered Nurse [Rehabilitation]','NUCC Provider Codes'),
   ('163WX0106X','Registered Nurse [Occupational Health]','NUCC Provider Codes'),
   ('163WD0400X','Registered Nurse [Diabetes Educator]','NUCC Provider Codes'),
   ('163WE0900X','Registered Nurse [Enterostomal Therapy]','NUCC Provider Codes'),
   ('163WN0800X','Registered Nurse [Neuroscience]','NUCC Provider Codes'),
   ('163WW0101X','Registered Nurse [Women''s Health Care, Ambulatory]','NUCC Provider Codes'),
   ('163WR1000X','Registered Nurse [Reproductive Endocrinology/Infertility]','NUCC Provider Codes'),
   ('163WM0102X','Registered Nurse [Maternal Newborn]','NUCC Provider Codes'),
   ('163WS0200X','Registered Nurse [School]','NUCC Provider Codes'),
   ('163WM1400X','Registered Nurse [Nurse Massage Therapist (NMT)]','NUCC Provider Codes'),
   ('163WP0000X','Registered Nurse [Pain Management]','NUCC Provider Codes'),
   ('163WN0002X','Registered Nurse [Neonatal Intensive Care]','NUCC Provider Codes'),
   ('163WN1003X','Registered Nurse [Nutrition Support]','NUCC Provider Codes'),
   ('163W00000X','Registered Nurse','NUCC Provider Codes'),
   ('163WP0809X','Registered Nurse [Psychiatric/Mental Health, Adult]','NUCC Provider Codes'),
   ('163WC1400X','Registered Nurse [College Health]','NUCC Provider Codes'),
   ('163WI0600X','Registered Nurse [Infection Control]','NUCC Provider Codes'),
   ('163WI0500X','Registered Nurse [Infusion Therapy]','NUCC Provider Codes'),
   ('163WX0002X','Registered Nurse [Obstetric, High-Risk]','NUCC Provider Codes'),
   ('163WX0601X','Registered Nurse [Otorhinolaryngology & Head-Neck]','NUCC Provider Codes'),
   ('163WX1500X','Registered Nurse [Ostomy Care]','NUCC Provider Codes'),
   ('163WE0003X','Registered Nurse [Emergency]','NUCC Provider Codes'),
   ('163WX0200X','Registered Nurse [Oncology]','NUCC Provider Codes'),
   ('163WH0500X','Registered Nurse [Hemodialysis]','NUCC Provider Codes'),
   ('163WX0800X','Registered Nurse [Orthopedic]','NUCC Provider Codes'),
   ('163WX0003X','Registered Nurse [Obstetric, Inpatient]','NUCC Provider Codes'),
   ('163WP1700X','Registered Nurse [Perinatal]','NUCC Provider Codes'),
   ('163WC0400X','Registered Nurse [Case Management]','NUCC Provider Codes'),
   ('163WC3500X','Registered Nurse [Cardiac Rehabilitation]','NUCC Provider Codes'),
   ('163WC0200X','Registered Nurse [Critical Care Medicine]','NUCC Provider Codes'),
   ('163WD1100X','Registered Nurse [Dialysis, Peritoneal]','NUCC Provider Codes'),
   ('163WL0100X','Registered Nurse [Lactation Consultant]','NUCC Provider Codes'),
   ('163WC1500X','Registered Nurse [Community Health]','NUCC Provider Codes'),
   ('163WG0600X','Registered Nurse [Gerontology]','NUCC Provider Codes'),
   ('163WH0200X','Registered Nurse [Home Health]','NUCC Provider Codes'),
   ('163WR0006X','Registered Nurse [Registered Nurse First Assistant]','NUCC Provider Codes'),
   ('163WH1000X','Registered Nurse [Hospice]','NUCC Provider Codes'),
   ('163WN0300X','Registered Nurse [Nephrology]','NUCC Provider Codes'),
   ('163WC1600X','Registered Nurse [Continuing Education/Staff Development]','NUCC Provider Codes'),
   ('163WG0100X','Registered Nurse [Gastroenterology]','NUCC Provider Codes'),
   ('163WF0300X','Registered Nurse [Flight]','NUCC Provider Codes'),
   ('163WP0218X','Registered Nurse [Pediatric Oncology]','NUCC Provider Codes'),
   ('163WS0121X','Registered Nurse [Plastic Surgery]','NUCC Provider Codes'),
   ('163WA0400X','Registered Nurse [Addiction (Substance Use Disorder)]','NUCC Provider Codes'),
   ('163WX1100X','Registered Nurse [Ophthalmic]','NUCC Provider Codes'),
   ('163WW0000X','Registered Nurse [Wound Care]','NUCC Provider Codes'),
   ('163WP0200X','Registered Nurse [Pediatrics]','NUCC Provider Codes'),
   ('163WP0808X','Registered Nurse [Psychiatric/Mental Health]','NUCC Provider Codes'),
   ('163WA2000X','Registered Nurse [Administrator]','NUCC Provider Codes'),
   ('163WP2201X','Registered Nurse [Ambulatory Care]','NUCC Provider Codes'),
   ('163WU0100X','Registered Nurse [Urology]','NUCC Provider Codes'),
   ('163WG0000X','Registered Nurse [General Practice]','NUCC Provider Codes'),
   ('163WM0705X','Registered Nurse [Medical-Surgical]','NUCC Provider Codes'),
   ('163WC2100X','Registered Nurse [Continence Care]','NUCC Provider Codes'),
   ('163WP0807X','Registered Nurse [Psychiatric/Mental Health, Child & Adolescent]','NUCC Provider Codes'),
   ('225CX0006X','Rehabilitation Counselor [Orientation and Mobility Training Provider]','NUCC Provider Codes'),
   ('225CA2400X','Rehabilitation Counselor [Assistive Technology Practitioner]','NUCC Provider Codes'),
   ('225CA2500X','Rehabilitation Counselor [Assistive Technology Supplier]','NUCC Provider Codes'),
   ('225C00000X','Rehabilitation Counselor','NUCC Provider Codes'),
   ('283X00000X','Rehabilitation Hospital','NUCC Provider Codes'),
   ('283XC2000X','Rehabilitation Hospital [Children]','NUCC Provider Codes'),
   ('225400000X','Rehabilitation Practitioner','NUCC Provider Codes'),
   ('273Y00000X','Rehabilitation Unit','NUCC Provider Codes'),
   ('276400000X','Rehabilitation, Substance Use Disorder Unit','NUCC Provider Codes'),
   ('282J00000X','Religious Nonmedical Health Care Institution','NUCC Provider Codes'),
   ('374T00000X','Religious Nonmedical Nursing Personnel','NUCC Provider Codes'),
   ('374K00000X','Religious Nonmedical Practitioner','NUCC Provider Codes'),
   ('322D00000X','Residential Treatment Facility, Emotionally Disturbed Children','NUCC Provider Codes'),
   ('320600000X','Residential Treatment Facility, Mental Retardation and/or Developmental  Disabilities','NUCC Provider Codes'),
   ('320700000X','Residential Treatment Facility, Physical Disabilities','NUCC Provider Codes'),
   ('2278C0205X','Respiratory Therapist, Certified [Critical Care]','NUCC Provider Codes'),
   ('2278P3900X','Respiratory Therapist, Certified [Neonatal/Pediatrics]','NUCC Provider Codes'),
   ('2278P3800X','Respiratory Therapist, Certified [Palliative/Hospice]','NUCC Provider Codes'),
   ('2278H0200X','Respiratory Therapist, Certified [Home Health]','NUCC Provider Codes'),
   ('2278G1100X','Respiratory Therapist, Certified [General Care]','NUCC Provider Codes'),
   ('227800000X','Respiratory Therapist, Certified','NUCC Provider Codes'),
   ('2278P1006X','Respiratory Therapist, Certified [Pulmonary Function Technologist]','NUCC Provider Codes'),
   ('2278P4000X','Respiratory Therapist, Certified [Patient Transport]','NUCC Provider Codes'),
   ('2278G0305X','Respiratory Therapist, Certified [Geriatric Care]','NUCC Provider Codes'),
   ('2278P1004X','Respiratory Therapist, Certified [Pulmonary Diagnostics]','NUCC Provider Codes'),
   ('2278E0002X','Respiratory Therapist, Certified [Emergency Care]','NUCC Provider Codes'),
   ('2278E1000X','Respiratory Therapist, Certified [Educational]','NUCC Provider Codes'),
   ('2278S1500X','Respiratory Therapist, Certified [SNF/Subacute Care]','NUCC Provider Codes'),
   ('2278P1005X','Respiratory Therapist, Certified [Pulmonary Rehabilitation]','NUCC Provider Codes'),
   ('2279P4000X','Respiratory Therapist, Registered [Patient Transport]','NUCC Provider Codes'),
   ('2279P1006X','Respiratory Therapist, Registered [Pulmonary Function Technologist]','NUCC Provider Codes'),
   ('2279C0205X','Respiratory Therapist, Registered [Critical Care]','NUCC Provider Codes'),
   ('2279G1100X','Respiratory Therapist, Registered [General Care]','NUCC Provider Codes'),
   ('2279P1005X','Respiratory Therapist, Registered [Pulmonary Rehabilitation]','NUCC Provider Codes'),
   ('2279P3900X','Respiratory Therapist, Registered [Neonatal/Pediatrics]','NUCC Provider Codes'),
   ('2279E0002X','Respiratory Therapist, Registered [Emergency Care]','NUCC Provider Codes'),
   ('2279G0305X','Respiratory Therapist, Registered [Geriatric Care]','NUCC Provider Codes'),
   ('2279P3800X','Respiratory Therapist, Registered [Palliative/Hospice]','NUCC Provider Codes'),
   ('2279P1004X','Respiratory Therapist, Registered [Pulmonary Diagnostics]','NUCC Provider Codes'),
   ('227900000X','Respiratory Therapist, Registered','NUCC Provider Codes'),
   ('2279E1000X','Respiratory Therapist, Registered [Educational]','NUCC Provider Codes'),
   ('2279S1500X','Respiratory Therapist, Registered [SNF/Subacute Care]','NUCC Provider Codes'),
   ('2279H0200X','Respiratory Therapist, Registered [Home Health]','NUCC Provider Codes'),
   ('385HR2065X','Respite Care [Respite Care, Physical Disabilities, Child]','NUCC Provider Codes'),
   ('385HR2060X','Respite Care [Respite Care, Mental Retardation and/or Developmental Disabilities]','NUCC Provider Codes'),
   ('385HR2055X','Respite Care [Respite Care, Mental Illness, Child]','NUCC Provider Codes'),
   ('385H00000X','Respite Care','NUCC Provider Codes'),
   ('385HR2050X','Respite Care [Respite Care Camp]','NUCC Provider Codes'),
   ('343800000X','Secured Medical Transport (VAN)','NUCC Provider Codes'),
   ('193400000X','Single Specialty','NUCC Provider Codes'),
   ('314000000X','Skilled Nursing Facility','NUCC Provider Codes'),
   ('3140N1450X','Skilled Nursing Facility [Nursing Care, Pediatric]','NUCC Provider Codes'),
   ('173F00000X','Sleep Specialist, PhD','NUCC Provider Codes'),
   ('1041S0200X','Social Worker [School]','NUCC Provider Codes'),
   ('104100000X','Social Worker','NUCC Provider Codes'),
   ('1041C0700X','Social Worker [Clinical]','NUCC Provider Codes'),
   ('284300000X','Special Hospital','NUCC Provider Codes'),
   ('174400000X','Specialist','NUCC Provider Codes'),
   ('1744P3200X','Specialist [Prosthetics Case Management]','NUCC Provider Codes'),
   ('1744G0900X','Specialist [Graphics Designer]','NUCC Provider Codes'),
   ('1744R1102X','Specialist [Research Study]','NUCC Provider Codes'),
   ('1744R1103X','Specialist [Research Data Abstracter/Coder]','NUCC Provider Codes'),
   ('2255R0406X','Specialist/Technologist [Rehabilitation, Blind]','NUCC Provider Codes'),
   ('225500000X','Specialist/Technologist','NUCC Provider Codes'),
   ('2255A2300X','Specialist/Technologist [Athletic Trainer]','NUCC Provider Codes'),
   ('235500000X','Specialist/Technologist','NUCC Provider Codes'),
   ('2355S0801X','Specialist/Technologist [Speech-Language Assistant]','NUCC Provider Codes'),
   ('2355A2700X','Specialist/Technologist [Audiology Assistant]','NUCC Provider Codes'),
   ('246X00000X','Specialist/Technologist Cardiovascular','NUCC Provider Codes'),
   ('246XC2901X','Specialist/Technologist Cardiovascular [Cardiovascular Invasive Specialist]','NUCC Provider Codes'),
   ('246XC2903X','Specialist/Technologist Cardiovascular [Vascular Specialist]','NUCC Provider Codes'),
   ('246XS1301X','Specialist/Technologist Cardiovascular [Sonography]','NUCC Provider Codes'),
   ('246YC3301X','Specialist/Technologist, Health Information [Coding Specialist, Hospital  Based]','NUCC Provider Codes'),
   ('246YC3302X','Specialist/Technologist, Health Information [Coding Specialist, Physician  Office Based]','NUCC Provider Codes'),
   ('246Y00000X','Specialist/Technologist, Health Information','NUCC Provider Codes'),
   ('246YR1600X','Specialist/Technologist, Health Information [Registered Record Administrator]','NUCC Provider Codes'),
   ('246ZX2200X','Specialist/Technologist, Other [Orthopedic Assistant]','NUCC Provider Codes'),
   ('246ZI1000X','Specialist/Technologist, Other [Illustration, Medical]','NUCC Provider Codes'),
   ('246ZG0701X','Specialist/Technologist, Other [Graphics Methods]','NUCC Provider Codes'),
   ('246Z00000X','Specialist/Technologist, Other','NUCC Provider Codes'),
   ('246ZE0500X','Specialist/Technologist, Other [EEG]','NUCC Provider Codes'),
   ('246ZN0300X','Specialist/Technologist, Other [Nephrology]','NUCC Provider Codes'),
   ('246ZE0600X','Specialist/Technologist, Other [Electroneurodiagnostic]','NUCC Provider Codes'),
   ('246ZC0007X','Specialist/Technologist, Other [Surgical Assistant]','NUCC Provider Codes'),
   ('246ZB0302X','Specialist/Technologist, Other [Biomedical Photographer]','NUCC Provider Codes'),
   ('246ZA2600X','Specialist/Technologist, Other [Art, Medical]','NUCC Provider Codes'),
   ('246ZG1000X','Specialist/Technologist, Other [Geneticist, Medical (PhD)]','NUCC Provider Codes'),
   ('246ZB0301X','Specialist/Technologist, Other [Biomedical Engineering]','NUCC Provider Codes'),
   ('246ZS0410X','Specialist/Technologist, Other [Surgical Technologist]','NUCC Provider Codes'),
   ('246ZB0500X','Specialist/Technologist, Other [Biochemist]','NUCC Provider Codes'),
   ('246ZB0600X','Specialist/Technologist, Other [Biostatistician]','NUCC Provider Codes'),
   ('246QL0900X','Specialist/Technologist, Pathology [Laboratory Management]','NUCC Provider Codes'),
   ('246QI0000X','Specialist/Technologist, Pathology [Immunology]','NUCC Provider Codes'),
   ('246QC2700X','Specialist/Technologist, Pathology [Cytotechnology]','NUCC Provider Codes'),
   ('246QM0706X','Specialist/Technologist, Pathology [Medical Technologist]','NUCC Provider Codes'),
   ('246QB0000X','Specialist/Technologist, Pathology [Blood Banking]','NUCC Provider Codes'),
   ('246Q00000X','Specialist/Technologist, Pathology','NUCC Provider Codes'),
   ('246QH0000X','Specialist/Technologist, Pathology [Hematology]','NUCC Provider Codes'),
   ('246QH0600X','Specialist/Technologist, Pathology [Histology]','NUCC Provider Codes'),
   ('246QL0901X','Specialist/Technologist, Pathology [Laboratory Management, Diplomate]','NUCC Provider Codes'),
   ('246QH0401X','Specialist/Technologist, Pathology [Hemapheresis Practitioner]','NUCC Provider Codes'),
   ('246QC1000X','Specialist/Technologist, Pathology [Chemistry]','NUCC Provider Codes'),
   ('246QM0900X','Specialist/Technologist, Pathology [Microbiology]','NUCC Provider Codes'),
   ('235Z00000X','Speech-Language Pathologist','NUCC Provider Codes'),
   ('390200000X','Student in an Organized Health Care Education/Training Program','NUCC Provider Codes'),
   ('324500000X','Substance Abuse Rehabilitation Facility','NUCC Provider Codes'),
   ('3245S0500X','Substance Abuse Rehabilitation Facility [Substance Abuse Treatment, Children]','NUCC Provider Codes'),
   ('251X00000X','Supports Brokerage','NUCC Provider Codes'),
   ('208600000X','Surgery','NUCC Provider Codes'),
   ('2086X0206X','Surgery [Surgical Oncology]','NUCC Provider Codes'),
   ('2086S0127X','Surgery [Trauma Surgery]','NUCC Provider Codes'),
   ('2086H0002X','Surgery [Hospice and Palliative Medicine]','NUCC Provider Codes'),
   ('2086S0105X','Surgery [Surgery of the Hand]','NUCC Provider Codes'),
   ('2086S0122X','Surgery [Plastic and Reconstructive Surgery]','NUCC Provider Codes'),
   ('2086S0102X','Surgery [Surgical Critical Care]','NUCC Provider Codes'),
   ('2086S0120X','Surgery [Pediatric Surgery]','NUCC Provider Codes'),
   ('2086S0129X','Surgery [Vascular Surgery]','NUCC Provider Codes'),
   ('344600000X','Taxi','NUCC Provider Codes'),
   ('3747A0650X','Technician [Attendant Care Provider]','NUCC Provider Codes'),
   ('374700000X','Technician','NUCC Provider Codes'),
   ('3747P1801X','Technician [Personal Care Attendant]','NUCC Provider Codes'),
   ('246W00000X','Technician, Cardiology','NUCC Provider Codes'),
   ('247000000X','Technician, Health Information','NUCC Provider Codes'),
   ('2470A2800X','Technician, Health Information [Assistant Record Technician]','NUCC Provider Codes'),
   ('2472V0600X','Technician, Other [Veterinary]','NUCC Provider Codes'),
   ('2472B0301X','Technician, Other [Biomedical Engineering]','NUCC Provider Codes'),
   ('2472R0900X','Technician, Other [Renal Dialysis]','NUCC Provider Codes'),
   ('2472D0500X','Technician, Other [Darkroom]','NUCC Provider Codes'),
   ('2472E0500X','Technician, Other [EEG]','NUCC Provider Codes'),
   ('247200000X','Technician, Other','NUCC Provider Codes'),
   ('246R00000X','Technician, Pathology','NUCC Provider Codes'),
   ('246RH0600X','Technician, Pathology [Histology]','NUCC Provider Codes'),
   ('246RP1900X','Technician, Pathology [Phlebotomy]','NUCC Provider Codes'),
   ('246RM2200X','Technician, Pathology [Medical Laboratory]','NUCC Provider Codes'),
   ('156FX1202X','Technician/Technologist [Optometric Technician]','NUCC Provider Codes'),
   ('156FX1201X','Technician/Technologist [Optometric Assistant]','NUCC Provider Codes'),
   ('156FX1101X','Technician/Technologist [Ophthalmic Assistant]','NUCC Provider Codes'),
   ('156FC0800X','Technician/Technologist [Contact Lens]','NUCC Provider Codes'),
   ('156FX1700X','Technician/Technologist [Ocularist]','NUCC Provider Codes'),
   ('156FX1100X','Technician/Technologist [Ophthalmic]','NUCC Provider Codes'),
   ('156FC0801X','Technician/Technologist [Contact Lens Fitter]','NUCC Provider Codes'),
   ('156FX1900X','Technician/Technologist [Orthoptist]','NUCC Provider Codes'),
   ('156F00000X','Technician/Technologist','NUCC Provider Codes'),
   ('156FX1800X','Technician/Technologist [Optician]','NUCC Provider Codes'),
   ('208G00000X','Thoracic Surgery (Cardiothoracic Vascular Surgery)','NUCC Provider Codes'),
   ('347D00000X','Train','NUCC Provider Codes'),
   ('204F00000X','Transplant Surgery','NUCC Provider Codes'),
   ('347E00000X','Transportation Broker','NUCC Provider Codes'),
   ('2088F0040X','Urology [Female Pelvic Medicine and Reconstructive Surgery]','NUCC Provider Codes'),
   ('2088P0231X','Urology [Pediatric Urology]','NUCC Provider Codes'),
   ('208800000X','Urology','NUCC Provider Codes'),
   ('174MM1900X','Veterinarian [Medical Research]','NUCC Provider Codes'),
   ('174M00000X','Veterinarian','NUCC Provider Codes'),
   ('251V00000X','Voluntary or Charitable','NUCC Provider Codes')
GO

-- update this so we know where the code came from...
UPDATE [Provider].[Provider_Code]
   SET Data_Owner_ID = 'NUCC',
       Agency_Reporting_ID = 'CDC',
       Version_Number = 'v5'
GO